/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ChangeNicknameRequest } from '../models';
// @ts-ignore
import type { ChangePasswordRequest } from '../models';
// @ts-ignore
import type { CheckEmail200Response } from '../models';
// @ts-ignore
import type { CheckEmail409Response } from '../models';
// @ts-ignore
import type { CheckPasswordRequest } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { GoogleLoginRequest } from '../models';
// @ts-ignore
import type { KakaoLoginRequest } from '../models';
// @ts-ignore
import type { Login200Response } from '../models';
// @ts-ignore
import type { LoginRequest } from '../models';
// @ts-ignore
import type { NaverLoginRequest } from '../models';
// @ts-ignore
import type { ReissueToken200Response } from '../models';
// @ts-ignore
import type { ReissueTokenRequest } from '../models';
// @ts-ignore
import type { Signup200Response } from '../models';
// @ts-ignore
import type { SignupRequest } from '../models';
// @ts-ignore
import type { SuccessResponse } from '../models';
// @ts-ignore
import type { UpdateBioRequest } from '../models';
/**
 * AuthenticationApi - axios parameter creator
 * @export
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 인증된 사용자가 자신의 닉네임을 변경합니다. 새로운 닉네임은 다른 사용자가 사용하고 있지 않은 고유한 값이어야 합니다. 변경 전 \'닉네임 중복 검사\' API(GET /auth/check-nickname)를 통해 사용 가능 여부를 확인할 수 있습니다.
         * @summary 닉네임 변경
         * @param {ChangeNicknameRequest} [changeNicknameRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changeNickname: async (changeNicknameRequest?: ChangeNicknameRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/nickname`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(changeNicknameRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 인증된 사용자가 자신의 계정 비밀번호를 변경합니다. 보안을 위해, 이 API를 호출하기 전에 먼저 \'비밀번호 확인\' API(POST /auth/check-password)를 통해 사용자 인증을 완료하는 것을 권장합니다.
         * @summary 비밀번호 변경
         * @param {ChangePasswordRequest} [changePasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword: async (changePasswordRequest?: ChangePasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(changePasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 회원가입 과정에서 사용자가 입력한 이메일이 이미 데이터베이스에 존재하는지 확인합니다. 중복 여부에 따라 사용 가능 상태를 boolean 값으로 반환합니다.
         * @summary 이메일 중복 검사
         * @param {string} email 확인할 이메일
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkEmail: async (email: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            assertParamExists('checkEmail', 'email', email)
            const localVarPath = `/auth/check-email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 회원가입 또는 닉네임 변경 과정에서 사용자가 입력한 닉네임이 이미 사용 중인지 확인합니다. 중복 여부에 따라 사용 가능 상태를 boolean 값으로 반환합니다.
         * @summary 닉네임 중복 검사
         * @param {string} nickname 중복 확인할 닉네임
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkNickname: async (nickname: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'nickname' is not null or undefined
            assertParamExists('checkNickname', 'nickname', nickname)
            const localVarPath = `/auth/check-nickname`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (nickname !== undefined) {
                localVarQueryParameter['nickname'] = nickname;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 사용자가 비밀번호 변경 등 민감한 작업을 수행하기 전에, 현재 로그인된 계정의 소유주가 맞는지 확인하기 위해 현재 비밀번호를 입력받아 검증합니다. 인증된 사용자만 호출할 수 있습니다.
         * @summary 비밀번호 확인
         * @param {CheckPasswordRequest} [checkPasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkPassword: async (checkPasswordRequest?: CheckPasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/check-password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(checkPasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 구글에서 발급받은 OAuth AccessToken을 사용하여 서비스에 로그인 또는 회원가입을 처리합니다. 기존에 해당 소셜 계정으로 가입한 사용자가 없으면 신규 계정을 생성하고, 있으면 로그인을 진행합니다. 성공 시, 서비스의 AccessToken과 RefreshToken을 발급합니다.
         * @summary 구글 소셜 로그인
         * @param {GoogleLoginRequest} [googleLoginRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        googleLogin: async (googleLoginRequest?: GoogleLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/oauth/google`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(googleLoginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 카카오에서 발급받은 OAuth AccessToken을 사용하여 서비스에 로그인 또는 회원가입을 처리합니다. 기존에 해당 소셜 계정으로 가입한 사용자가 없으면 신규 계정을 생성하고, 있으면 로그인을 진행합니다. 성공 시, 서비스의 AccessToken과 RefreshToken을 발급합니다.
         * @summary 카카오 소셜 로그인
         * @param {KakaoLoginRequest} [kakaoLoginRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        kakaoLogin: async (kakaoLoginRequest?: KakaoLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/oauth/kakao`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(kakaoLoginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 이메일과 비밀번호를 사용하여 로컬 계정으로 로그인합니다.  - 로그인 성공 시, API 접근에 필요한 AccessToken과 RefreshToken을 포함한 인증 정보를 반환합니다.  - RefreshToken은 AccessToken이 만료되었을 때 새로운 토큰을 발급받는 데 사용됩니다.
         * @summary 로컬 로그인
         * @param {LoginRequest} [loginRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginRequest?: LoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 사용자를 로그아웃 처리합니다. 서버는 요청 헤더의 `Authorization` 필드에서 AccessToken을 추출하여 해당 토큰을 더 이상 사용하지 못하도록 블랙리스트에 추가합니다. RefreshToken 또한 서버와 클라이언트 양쪽에서 무효화되어야 합니다.
         * @summary 로그아웃
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 네이버에서 발급받은 OAuth AccessToken을 사용하여 서비스에 로그인 또는 회원가입을 처리합니다. 기존에 해당 소셜 계정으로 가입한 사용자가 없으면 신규 계정을 생성하고, 있으면 로그인을 진행합니다. 성공 시, 서비스의 AccessToken과 RefreshToken을 발급합니다.
         * @summary 네이버 소셜 로그인
         * @param {NaverLoginRequest} [naverLoginRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        naverLogin: async (naverLoginRequest?: NaverLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/oauth/naver`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(naverLoginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 만료된 AccessToken을 새로운 토큰으로 교체합니다.  - 클라이언트는 유효한 RefreshToken을 요청 본문에 담아 보내야 합니다.  - 서버는 RefreshToken을 검증한 후, 유효할 경우 새로운 AccessToken을 발급하여 반환합니다.
         * @summary 토큰 재발급
         * @param {ReissueTokenRequest} [reissueTokenRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reissueToken: async (reissueTokenRequest?: ReissueTokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/reissue`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reissueTokenRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 사용자의 이메일, 비밀번호, 닉네임을 사용하여 새로운 계정을 생성합니다.  - 이메일과 닉네임의 중복 여부는 별도의 API(GET /auth/check-email, GET /auth/check-nickname)를 통해 미리 검증된 상태이다. - 회원가입 성공 시, 생성된 사용자의 고유 ID와 기본 정보를 반환합니다.
         * @summary 이메일 회원가입
         * @param {SignupRequest} [signupRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signup: async (signupRequest?: SignupRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signupRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 인증된 사용자가 자신의 프로필 페이지에 표시될 소개글(bio)을 수정합니다. 최대 500자까지 입력할 수 있습니다.
         * @summary 소개글 업데이트
         * @param {UpdateBioRequest} [updateBioRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBio: async (updateBioRequest?: UpdateBioRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/bio`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateBioRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 인증된 사용자가 자신의 프로필 이미지를 변경합니다.  파일을 보내서 서버에서 파일 url을 구한뒤, 프론트로 보내지 않고 db에만 업데이트를 수행합니다 /upload-image 경로와 같이 파일을 보내지만 , 돌아오는 응답은 db에 파일의 url경로가 적용되었는지만 확인됩니다.(url 반환 없음)
         * @summary 프로필 이미지 업데이트
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProfileImage: async (file?: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/profile-img`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 * @export
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * 인증된 사용자가 자신의 닉네임을 변경합니다. 새로운 닉네임은 다른 사용자가 사용하고 있지 않은 고유한 값이어야 합니다. 변경 전 \'닉네임 중복 검사\' API(GET /auth/check-nickname)를 통해 사용 가능 여부를 확인할 수 있습니다.
         * @summary 닉네임 변경
         * @param {ChangeNicknameRequest} [changeNicknameRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changeNickname(changeNicknameRequest?: ChangeNicknameRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changeNickname(changeNicknameRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.changeNickname']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 인증된 사용자가 자신의 계정 비밀번호를 변경합니다. 보안을 위해, 이 API를 호출하기 전에 먼저 \'비밀번호 확인\' API(POST /auth/check-password)를 통해 사용자 인증을 완료하는 것을 권장합니다.
         * @summary 비밀번호 변경
         * @param {ChangePasswordRequest} [changePasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changePassword(changePasswordRequest?: ChangePasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changePassword(changePasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.changePassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 회원가입 과정에서 사용자가 입력한 이메일이 이미 데이터베이스에 존재하는지 확인합니다. 중복 여부에 따라 사용 가능 상태를 boolean 값으로 반환합니다.
         * @summary 이메일 중복 검사
         * @param {string} email 확인할 이메일
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkEmail(email: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CheckEmail200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkEmail(email, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.checkEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 회원가입 또는 닉네임 변경 과정에서 사용자가 입력한 닉네임이 이미 사용 중인지 확인합니다. 중복 여부에 따라 사용 가능 상태를 boolean 값으로 반환합니다.
         * @summary 닉네임 중복 검사
         * @param {string} nickname 중복 확인할 닉네임
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkNickname(nickname: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CheckEmail200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkNickname(nickname, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.checkNickname']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 사용자가 비밀번호 변경 등 민감한 작업을 수행하기 전에, 현재 로그인된 계정의 소유주가 맞는지 확인하기 위해 현재 비밀번호를 입력받아 검증합니다. 인증된 사용자만 호출할 수 있습니다.
         * @summary 비밀번호 확인
         * @param {CheckPasswordRequest} [checkPasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkPassword(checkPasswordRequest?: CheckPasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkPassword(checkPasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.checkPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 구글에서 발급받은 OAuth AccessToken을 사용하여 서비스에 로그인 또는 회원가입을 처리합니다. 기존에 해당 소셜 계정으로 가입한 사용자가 없으면 신규 계정을 생성하고, 있으면 로그인을 진행합니다. 성공 시, 서비스의 AccessToken과 RefreshToken을 발급합니다.
         * @summary 구글 소셜 로그인
         * @param {GoogleLoginRequest} [googleLoginRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async googleLogin(googleLoginRequest?: GoogleLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Login200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.googleLogin(googleLoginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.googleLogin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 카카오에서 발급받은 OAuth AccessToken을 사용하여 서비스에 로그인 또는 회원가입을 처리합니다. 기존에 해당 소셜 계정으로 가입한 사용자가 없으면 신규 계정을 생성하고, 있으면 로그인을 진행합니다. 성공 시, 서비스의 AccessToken과 RefreshToken을 발급합니다.
         * @summary 카카오 소셜 로그인
         * @param {KakaoLoginRequest} [kakaoLoginRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async kakaoLogin(kakaoLoginRequest?: KakaoLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Login200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.kakaoLogin(kakaoLoginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.kakaoLogin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 이메일과 비밀번호를 사용하여 로컬 계정으로 로그인합니다.  - 로그인 성공 시, API 접근에 필요한 AccessToken과 RefreshToken을 포함한 인증 정보를 반환합니다.  - RefreshToken은 AccessToken이 만료되었을 때 새로운 토큰을 발급받는 데 사용됩니다.
         * @summary 로컬 로그인
         * @param {LoginRequest} [loginRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginRequest?: LoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Login200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 사용자를 로그아웃 처리합니다. 서버는 요청 헤더의 `Authorization` 필드에서 AccessToken을 추출하여 해당 토큰을 더 이상 사용하지 못하도록 블랙리스트에 추가합니다. RefreshToken 또한 서버와 클라이언트 양쪽에서 무효화되어야 합니다.
         * @summary 로그아웃
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.logout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 네이버에서 발급받은 OAuth AccessToken을 사용하여 서비스에 로그인 또는 회원가입을 처리합니다. 기존에 해당 소셜 계정으로 가입한 사용자가 없으면 신규 계정을 생성하고, 있으면 로그인을 진행합니다. 성공 시, 서비스의 AccessToken과 RefreshToken을 발급합니다.
         * @summary 네이버 소셜 로그인
         * @param {NaverLoginRequest} [naverLoginRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async naverLogin(naverLoginRequest?: NaverLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Login200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.naverLogin(naverLoginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.naverLogin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 만료된 AccessToken을 새로운 토큰으로 교체합니다.  - 클라이언트는 유효한 RefreshToken을 요청 본문에 담아 보내야 합니다.  - 서버는 RefreshToken을 검증한 후, 유효할 경우 새로운 AccessToken을 발급하여 반환합니다.
         * @summary 토큰 재발급
         * @param {ReissueTokenRequest} [reissueTokenRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reissueToken(reissueTokenRequest?: ReissueTokenRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReissueToken200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reissueToken(reissueTokenRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.reissueToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 사용자의 이메일, 비밀번호, 닉네임을 사용하여 새로운 계정을 생성합니다.  - 이메일과 닉네임의 중복 여부는 별도의 API(GET /auth/check-email, GET /auth/check-nickname)를 통해 미리 검증된 상태이다. - 회원가입 성공 시, 생성된 사용자의 고유 ID와 기본 정보를 반환합니다.
         * @summary 이메일 회원가입
         * @param {SignupRequest} [signupRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signup(signupRequest?: SignupRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Signup200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signup(signupRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.signup']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 인증된 사용자가 자신의 프로필 페이지에 표시될 소개글(bio)을 수정합니다. 최대 500자까지 입력할 수 있습니다.
         * @summary 소개글 업데이트
         * @param {UpdateBioRequest} [updateBioRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateBio(updateBioRequest?: UpdateBioRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateBio(updateBioRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.updateBio']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 인증된 사용자가 자신의 프로필 이미지를 변경합니다.  파일을 보내서 서버에서 파일 url을 구한뒤, 프론트로 보내지 않고 db에만 업데이트를 수행합니다 /upload-image 경로와 같이 파일을 보내지만 , 돌아오는 응답은 db에 파일의 url경로가 적용되었는지만 확인됩니다.(url 반환 없음)
         * @summary 프로필 이미지 업데이트
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProfileImage(file?: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProfileImage(file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.updateProfileImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 * @export
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * 인증된 사용자가 자신의 닉네임을 변경합니다. 새로운 닉네임은 다른 사용자가 사용하고 있지 않은 고유한 값이어야 합니다. 변경 전 \'닉네임 중복 검사\' API(GET /auth/check-nickname)를 통해 사용 가능 여부를 확인할 수 있습니다.
         * @summary 닉네임 변경
         * @param {ChangeNicknameRequest} [changeNicknameRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changeNickname(changeNicknameRequest?: ChangeNicknameRequest, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.changeNickname(changeNicknameRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 인증된 사용자가 자신의 계정 비밀번호를 변경합니다. 보안을 위해, 이 API를 호출하기 전에 먼저 \'비밀번호 확인\' API(POST /auth/check-password)를 통해 사용자 인증을 완료하는 것을 권장합니다.
         * @summary 비밀번호 변경
         * @param {ChangePasswordRequest} [changePasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword(changePasswordRequest?: ChangePasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.changePassword(changePasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 회원가입 과정에서 사용자가 입력한 이메일이 이미 데이터베이스에 존재하는지 확인합니다. 중복 여부에 따라 사용 가능 상태를 boolean 값으로 반환합니다.
         * @summary 이메일 중복 검사
         * @param {string} email 확인할 이메일
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkEmail(email: string, options?: RawAxiosRequestConfig): AxiosPromise<CheckEmail200Response> {
            return localVarFp.checkEmail(email, options).then((request) => request(axios, basePath));
        },
        /**
         * 회원가입 또는 닉네임 변경 과정에서 사용자가 입력한 닉네임이 이미 사용 중인지 확인합니다. 중복 여부에 따라 사용 가능 상태를 boolean 값으로 반환합니다.
         * @summary 닉네임 중복 검사
         * @param {string} nickname 중복 확인할 닉네임
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkNickname(nickname: string, options?: RawAxiosRequestConfig): AxiosPromise<CheckEmail200Response> {
            return localVarFp.checkNickname(nickname, options).then((request) => request(axios, basePath));
        },
        /**
         * 사용자가 비밀번호 변경 등 민감한 작업을 수행하기 전에, 현재 로그인된 계정의 소유주가 맞는지 확인하기 위해 현재 비밀번호를 입력받아 검증합니다. 인증된 사용자만 호출할 수 있습니다.
         * @summary 비밀번호 확인
         * @param {CheckPasswordRequest} [checkPasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkPassword(checkPasswordRequest?: CheckPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.checkPassword(checkPasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 구글에서 발급받은 OAuth AccessToken을 사용하여 서비스에 로그인 또는 회원가입을 처리합니다. 기존에 해당 소셜 계정으로 가입한 사용자가 없으면 신규 계정을 생성하고, 있으면 로그인을 진행합니다. 성공 시, 서비스의 AccessToken과 RefreshToken을 발급합니다.
         * @summary 구글 소셜 로그인
         * @param {GoogleLoginRequest} [googleLoginRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        googleLogin(googleLoginRequest?: GoogleLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<Login200Response> {
            return localVarFp.googleLogin(googleLoginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 카카오에서 발급받은 OAuth AccessToken을 사용하여 서비스에 로그인 또는 회원가입을 처리합니다. 기존에 해당 소셜 계정으로 가입한 사용자가 없으면 신규 계정을 생성하고, 있으면 로그인을 진행합니다. 성공 시, 서비스의 AccessToken과 RefreshToken을 발급합니다.
         * @summary 카카오 소셜 로그인
         * @param {KakaoLoginRequest} [kakaoLoginRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        kakaoLogin(kakaoLoginRequest?: KakaoLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<Login200Response> {
            return localVarFp.kakaoLogin(kakaoLoginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 이메일과 비밀번호를 사용하여 로컬 계정으로 로그인합니다.  - 로그인 성공 시, API 접근에 필요한 AccessToken과 RefreshToken을 포함한 인증 정보를 반환합니다.  - RefreshToken은 AccessToken이 만료되었을 때 새로운 토큰을 발급받는 데 사용됩니다.
         * @summary 로컬 로그인
         * @param {LoginRequest} [loginRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(loginRequest?: LoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<Login200Response> {
            return localVarFp.login(loginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 사용자를 로그아웃 처리합니다. 서버는 요청 헤더의 `Authorization` 필드에서 AccessToken을 추출하여 해당 토큰을 더 이상 사용하지 못하도록 블랙리스트에 추가합니다. RefreshToken 또한 서버와 클라이언트 양쪽에서 무효화되어야 합니다.
         * @summary 로그아웃
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.logout(options).then((request) => request(axios, basePath));
        },
        /**
         * 네이버에서 발급받은 OAuth AccessToken을 사용하여 서비스에 로그인 또는 회원가입을 처리합니다. 기존에 해당 소셜 계정으로 가입한 사용자가 없으면 신규 계정을 생성하고, 있으면 로그인을 진행합니다. 성공 시, 서비스의 AccessToken과 RefreshToken을 발급합니다.
         * @summary 네이버 소셜 로그인
         * @param {NaverLoginRequest} [naverLoginRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        naverLogin(naverLoginRequest?: NaverLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<Login200Response> {
            return localVarFp.naverLogin(naverLoginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 만료된 AccessToken을 새로운 토큰으로 교체합니다.  - 클라이언트는 유효한 RefreshToken을 요청 본문에 담아 보내야 합니다.  - 서버는 RefreshToken을 검증한 후, 유효할 경우 새로운 AccessToken을 발급하여 반환합니다.
         * @summary 토큰 재발급
         * @param {ReissueTokenRequest} [reissueTokenRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reissueToken(reissueTokenRequest?: ReissueTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReissueToken200Response> {
            return localVarFp.reissueToken(reissueTokenRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 사용자의 이메일, 비밀번호, 닉네임을 사용하여 새로운 계정을 생성합니다.  - 이메일과 닉네임의 중복 여부는 별도의 API(GET /auth/check-email, GET /auth/check-nickname)를 통해 미리 검증된 상태이다. - 회원가입 성공 시, 생성된 사용자의 고유 ID와 기본 정보를 반환합니다.
         * @summary 이메일 회원가입
         * @param {SignupRequest} [signupRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signup(signupRequest?: SignupRequest, options?: RawAxiosRequestConfig): AxiosPromise<Signup200Response> {
            return localVarFp.signup(signupRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 인증된 사용자가 자신의 프로필 페이지에 표시될 소개글(bio)을 수정합니다. 최대 500자까지 입력할 수 있습니다.
         * @summary 소개글 업데이트
         * @param {UpdateBioRequest} [updateBioRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBio(updateBioRequest?: UpdateBioRequest, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.updateBio(updateBioRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 인증된 사용자가 자신의 프로필 이미지를 변경합니다.  파일을 보내서 서버에서 파일 url을 구한뒤, 프론트로 보내지 않고 db에만 업데이트를 수행합니다 /upload-image 경로와 같이 파일을 보내지만 , 돌아오는 응답은 db에 파일의 url경로가 적용되었는지만 확인됩니다.(url 반환 없음)
         * @summary 프로필 이미지 업데이트
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProfileImage(file?: File, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.updateProfileImage(file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - object-oriented interface
 * @export
 * @class AuthenticationApi
 * @extends {BaseAPI}
 */
export class AuthenticationApi extends BaseAPI {
    /**
     * 인증된 사용자가 자신의 닉네임을 변경합니다. 새로운 닉네임은 다른 사용자가 사용하고 있지 않은 고유한 값이어야 합니다. 변경 전 \'닉네임 중복 검사\' API(GET /auth/check-nickname)를 통해 사용 가능 여부를 확인할 수 있습니다.
     * @summary 닉네임 변경
     * @param {ChangeNicknameRequest} [changeNicknameRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public changeNickname(changeNicknameRequest?: ChangeNicknameRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).changeNickname(changeNicknameRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 인증된 사용자가 자신의 계정 비밀번호를 변경합니다. 보안을 위해, 이 API를 호출하기 전에 먼저 \'비밀번호 확인\' API(POST /auth/check-password)를 통해 사용자 인증을 완료하는 것을 권장합니다.
     * @summary 비밀번호 변경
     * @param {ChangePasswordRequest} [changePasswordRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public changePassword(changePasswordRequest?: ChangePasswordRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).changePassword(changePasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 회원가입 과정에서 사용자가 입력한 이메일이 이미 데이터베이스에 존재하는지 확인합니다. 중복 여부에 따라 사용 가능 상태를 boolean 값으로 반환합니다.
     * @summary 이메일 중복 검사
     * @param {string} email 확인할 이메일
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public checkEmail(email: string, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).checkEmail(email, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 회원가입 또는 닉네임 변경 과정에서 사용자가 입력한 닉네임이 이미 사용 중인지 확인합니다. 중복 여부에 따라 사용 가능 상태를 boolean 값으로 반환합니다.
     * @summary 닉네임 중복 검사
     * @param {string} nickname 중복 확인할 닉네임
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public checkNickname(nickname: string, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).checkNickname(nickname, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 사용자가 비밀번호 변경 등 민감한 작업을 수행하기 전에, 현재 로그인된 계정의 소유주가 맞는지 확인하기 위해 현재 비밀번호를 입력받아 검증합니다. 인증된 사용자만 호출할 수 있습니다.
     * @summary 비밀번호 확인
     * @param {CheckPasswordRequest} [checkPasswordRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public checkPassword(checkPasswordRequest?: CheckPasswordRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).checkPassword(checkPasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 구글에서 발급받은 OAuth AccessToken을 사용하여 서비스에 로그인 또는 회원가입을 처리합니다. 기존에 해당 소셜 계정으로 가입한 사용자가 없으면 신규 계정을 생성하고, 있으면 로그인을 진행합니다. 성공 시, 서비스의 AccessToken과 RefreshToken을 발급합니다.
     * @summary 구글 소셜 로그인
     * @param {GoogleLoginRequest} [googleLoginRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public googleLogin(googleLoginRequest?: GoogleLoginRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).googleLogin(googleLoginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 카카오에서 발급받은 OAuth AccessToken을 사용하여 서비스에 로그인 또는 회원가입을 처리합니다. 기존에 해당 소셜 계정으로 가입한 사용자가 없으면 신규 계정을 생성하고, 있으면 로그인을 진행합니다. 성공 시, 서비스의 AccessToken과 RefreshToken을 발급합니다.
     * @summary 카카오 소셜 로그인
     * @param {KakaoLoginRequest} [kakaoLoginRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public kakaoLogin(kakaoLoginRequest?: KakaoLoginRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).kakaoLogin(kakaoLoginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 이메일과 비밀번호를 사용하여 로컬 계정으로 로그인합니다.  - 로그인 성공 시, API 접근에 필요한 AccessToken과 RefreshToken을 포함한 인증 정보를 반환합니다.  - RefreshToken은 AccessToken이 만료되었을 때 새로운 토큰을 발급받는 데 사용됩니다.
     * @summary 로컬 로그인
     * @param {LoginRequest} [loginRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public login(loginRequest?: LoginRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).login(loginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 사용자를 로그아웃 처리합니다. 서버는 요청 헤더의 `Authorization` 필드에서 AccessToken을 추출하여 해당 토큰을 더 이상 사용하지 못하도록 블랙리스트에 추가합니다. RefreshToken 또한 서버와 클라이언트 양쪽에서 무효화되어야 합니다.
     * @summary 로그아웃
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public logout(options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).logout(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 네이버에서 발급받은 OAuth AccessToken을 사용하여 서비스에 로그인 또는 회원가입을 처리합니다. 기존에 해당 소셜 계정으로 가입한 사용자가 없으면 신규 계정을 생성하고, 있으면 로그인을 진행합니다. 성공 시, 서비스의 AccessToken과 RefreshToken을 발급합니다.
     * @summary 네이버 소셜 로그인
     * @param {NaverLoginRequest} [naverLoginRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public naverLogin(naverLoginRequest?: NaverLoginRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).naverLogin(naverLoginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 만료된 AccessToken을 새로운 토큰으로 교체합니다.  - 클라이언트는 유효한 RefreshToken을 요청 본문에 담아 보내야 합니다.  - 서버는 RefreshToken을 검증한 후, 유효할 경우 새로운 AccessToken을 발급하여 반환합니다.
     * @summary 토큰 재발급
     * @param {ReissueTokenRequest} [reissueTokenRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public reissueToken(reissueTokenRequest?: ReissueTokenRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).reissueToken(reissueTokenRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 사용자의 이메일, 비밀번호, 닉네임을 사용하여 새로운 계정을 생성합니다.  - 이메일과 닉네임의 중복 여부는 별도의 API(GET /auth/check-email, GET /auth/check-nickname)를 통해 미리 검증된 상태이다. - 회원가입 성공 시, 생성된 사용자의 고유 ID와 기본 정보를 반환합니다.
     * @summary 이메일 회원가입
     * @param {SignupRequest} [signupRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public signup(signupRequest?: SignupRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).signup(signupRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 인증된 사용자가 자신의 프로필 페이지에 표시될 소개글(bio)을 수정합니다. 최대 500자까지 입력할 수 있습니다.
     * @summary 소개글 업데이트
     * @param {UpdateBioRequest} [updateBioRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public updateBio(updateBioRequest?: UpdateBioRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).updateBio(updateBioRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 인증된 사용자가 자신의 프로필 이미지를 변경합니다.  파일을 보내서 서버에서 파일 url을 구한뒤, 프론트로 보내지 않고 db에만 업데이트를 수행합니다 /upload-image 경로와 같이 파일을 보내지만 , 돌아오는 응답은 db에 파일의 url경로가 적용되었는지만 확인됩니다.(url 반환 없음)
     * @summary 프로필 이미지 업데이트
     * @param {File} [file] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public updateProfileImage(file?: File, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).updateProfileImage(file, options).then((request) => request(this.axios, this.basePath));
    }
}

