/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { ReissueToken200Response } from '../models';
// @ts-ignore
import type { ReissueTokenRequest } from '../models';
/**
 * AuthenticationTokenApi - axios parameter creator
 * @export
 */
export const AuthenticationTokenApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 만료된 AccessToken을 새로운 토큰으로 교체합니다.  - 클라이언트는 유효한 RefreshToken을 요청 본문에 담아 보내야 합니다.  - 서버는 RefreshToken을 검증한 후, 유효할 경우 새로운 AccessToken을 발급하여 반환합니다.
         * @summary 토큰 재발급
         * @param {ReissueTokenRequest} [reissueTokenRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reissueToken: async (reissueTokenRequest?: ReissueTokenRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/reissue`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reissueTokenRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationTokenApi - functional programming interface
 * @export
 */
export const AuthenticationTokenApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationTokenApiAxiosParamCreator(configuration)
    return {
        /**
         * 만료된 AccessToken을 새로운 토큰으로 교체합니다.  - 클라이언트는 유효한 RefreshToken을 요청 본문에 담아 보내야 합니다.  - 서버는 RefreshToken을 검증한 후, 유효할 경우 새로운 AccessToken을 발급하여 반환합니다.
         * @summary 토큰 재발급
         * @param {ReissueTokenRequest} [reissueTokenRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reissueToken(reissueTokenRequest?: ReissueTokenRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReissueToken200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reissueToken(reissueTokenRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationTokenApi.reissueToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationTokenApi - factory interface
 * @export
 */
export const AuthenticationTokenApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationTokenApiFp(configuration)
    return {
        /**
         * 만료된 AccessToken을 새로운 토큰으로 교체합니다.  - 클라이언트는 유효한 RefreshToken을 요청 본문에 담아 보내야 합니다.  - 서버는 RefreshToken을 검증한 후, 유효할 경우 새로운 AccessToken을 발급하여 반환합니다.
         * @summary 토큰 재발급
         * @param {ReissueTokenRequest} [reissueTokenRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reissueToken(reissueTokenRequest?: ReissueTokenRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReissueToken200Response> {
            return localVarFp.reissueToken(reissueTokenRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationTokenApi - object-oriented interface
 * @export
 * @class AuthenticationTokenApi
 * @extends {BaseAPI}
 */
export class AuthenticationTokenApi extends BaseAPI {
    /**
     * 만료된 AccessToken을 새로운 토큰으로 교체합니다.  - 클라이언트는 유효한 RefreshToken을 요청 본문에 담아 보내야 합니다.  - 서버는 RefreshToken을 검증한 후, 유효할 경우 새로운 AccessToken을 발급하여 반환합니다.
     * @summary 토큰 재발급
     * @param {ReissueTokenRequest} [reissueTokenRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationTokenApi
     */
    public reissueToken(reissueTokenRequest?: ReissueTokenRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationTokenApiFp(this.configuration).reissueToken(reissueTokenRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

