/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ChangeNicknameRequest } from '../models';
// @ts-ignore
import type { ChangePasswordRequest } from '../models';
// @ts-ignore
import type { CheckPasswordRequest } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { SuccessResponse } from '../models';
// @ts-ignore
import type { UpdateBioRequest } from '../models';
/**
 * AuthenticationUpdateInfoApi - axios parameter creator
 * @export
 */
export const AuthenticationUpdateInfoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 인증된 사용자가 자신의 닉네임을 변경합니다. 새로운 닉네임은 다른 사용자가 사용하고 있지 않은 고유한 값이어야 합니다. 변경 전 \'닉네임 중복 검사\' API(GET /auth/check-nickname)를 통해 사용 가능 여부를 확인할 수 있습니다.
         * @summary 닉네임 변경
         * @param {ChangeNicknameRequest} [changeNicknameRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changeNickname: async (changeNicknameRequest?: ChangeNicknameRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/nickname`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(changeNicknameRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 인증된 사용자가 자신의 계정 비밀번호를 변경합니다. 보안을 위해, 이 API를 호출하기 전에 먼저 \'비밀번호 확인\' API(POST /auth/check-password)를 통해 사용자 인증을 완료하는 것을 권장합니다.
         * @summary 비밀번호 변경
         * @param {ChangePasswordRequest} [changePasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword: async (changePasswordRequest?: ChangePasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(changePasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 사용자가 비밀번호 변경 등 민감한 작업을 수행하기 전에, 현재 로그인된 계정의 소유주가 맞는지 확인하기 위해 현재 비밀번호를 입력받아 검증합니다. 인증된 사용자만 호출할 수 있습니다.
         * @summary 비밀번호 확인
         * @param {CheckPasswordRequest} [checkPasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkPassword: async (checkPasswordRequest?: CheckPasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/check-password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(checkPasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 인증된 사용자가 자신의 프로필 페이지에 표시될 소개글(bio)을 수정합니다. 최대 500자까지 입력할 수 있습니다.
         * @summary 소개글 업데이트
         * @param {UpdateBioRequest} [updateBioRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBio: async (updateBioRequest?: UpdateBioRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/bio`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateBioRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 인증된 사용자가 자신의 프로필 이미지를 변경합니다. 이미지 파일 자체를 업로드하는 것이 아니라, \'이미지 업로드\' API(POST /upload-image)를 통해 얻은 이미지 URL을 전달하여 업데이트합니다.
         * @summary 프로필 이미지 업데이트
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProfileImage: async (file?: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/profile-img`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationUpdateInfoApi - functional programming interface
 * @export
 */
export const AuthenticationUpdateInfoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationUpdateInfoApiAxiosParamCreator(configuration)
    return {
        /**
         * 인증된 사용자가 자신의 닉네임을 변경합니다. 새로운 닉네임은 다른 사용자가 사용하고 있지 않은 고유한 값이어야 합니다. 변경 전 \'닉네임 중복 검사\' API(GET /auth/check-nickname)를 통해 사용 가능 여부를 확인할 수 있습니다.
         * @summary 닉네임 변경
         * @param {ChangeNicknameRequest} [changeNicknameRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changeNickname(changeNicknameRequest?: ChangeNicknameRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changeNickname(changeNicknameRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationUpdateInfoApi.changeNickname']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 인증된 사용자가 자신의 계정 비밀번호를 변경합니다. 보안을 위해, 이 API를 호출하기 전에 먼저 \'비밀번호 확인\' API(POST /auth/check-password)를 통해 사용자 인증을 완료하는 것을 권장합니다.
         * @summary 비밀번호 변경
         * @param {ChangePasswordRequest} [changePasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async changePassword(changePasswordRequest?: ChangePasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.changePassword(changePasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationUpdateInfoApi.changePassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 사용자가 비밀번호 변경 등 민감한 작업을 수행하기 전에, 현재 로그인된 계정의 소유주가 맞는지 확인하기 위해 현재 비밀번호를 입력받아 검증합니다. 인증된 사용자만 호출할 수 있습니다.
         * @summary 비밀번호 확인
         * @param {CheckPasswordRequest} [checkPasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkPassword(checkPasswordRequest?: CheckPasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkPassword(checkPasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationUpdateInfoApi.checkPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 인증된 사용자가 자신의 프로필 페이지에 표시될 소개글(bio)을 수정합니다. 최대 500자까지 입력할 수 있습니다.
         * @summary 소개글 업데이트
         * @param {UpdateBioRequest} [updateBioRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateBio(updateBioRequest?: UpdateBioRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateBio(updateBioRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationUpdateInfoApi.updateBio']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 인증된 사용자가 자신의 프로필 이미지를 변경합니다. 이미지 파일 자체를 업로드하는 것이 아니라, \'이미지 업로드\' API(POST /upload-image)를 통해 얻은 이미지 URL을 전달하여 업데이트합니다.
         * @summary 프로필 이미지 업데이트
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProfileImage(file?: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProfileImage(file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationUpdateInfoApi.updateProfileImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationUpdateInfoApi - factory interface
 * @export
 */
export const AuthenticationUpdateInfoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationUpdateInfoApiFp(configuration)
    return {
        /**
         * 인증된 사용자가 자신의 닉네임을 변경합니다. 새로운 닉네임은 다른 사용자가 사용하고 있지 않은 고유한 값이어야 합니다. 변경 전 \'닉네임 중복 검사\' API(GET /auth/check-nickname)를 통해 사용 가능 여부를 확인할 수 있습니다.
         * @summary 닉네임 변경
         * @param {ChangeNicknameRequest} [changeNicknameRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changeNickname(changeNicknameRequest?: ChangeNicknameRequest, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.changeNickname(changeNicknameRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 인증된 사용자가 자신의 계정 비밀번호를 변경합니다. 보안을 위해, 이 API를 호출하기 전에 먼저 \'비밀번호 확인\' API(POST /auth/check-password)를 통해 사용자 인증을 완료하는 것을 권장합니다.
         * @summary 비밀번호 변경
         * @param {ChangePasswordRequest} [changePasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        changePassword(changePasswordRequest?: ChangePasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.changePassword(changePasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 사용자가 비밀번호 변경 등 민감한 작업을 수행하기 전에, 현재 로그인된 계정의 소유주가 맞는지 확인하기 위해 현재 비밀번호를 입력받아 검증합니다. 인증된 사용자만 호출할 수 있습니다.
         * @summary 비밀번호 확인
         * @param {CheckPasswordRequest} [checkPasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkPassword(checkPasswordRequest?: CheckPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.checkPassword(checkPasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 인증된 사용자가 자신의 프로필 페이지에 표시될 소개글(bio)을 수정합니다. 최대 500자까지 입력할 수 있습니다.
         * @summary 소개글 업데이트
         * @param {UpdateBioRequest} [updateBioRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBio(updateBioRequest?: UpdateBioRequest, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.updateBio(updateBioRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 인증된 사용자가 자신의 프로필 이미지를 변경합니다. 이미지 파일 자체를 업로드하는 것이 아니라, \'이미지 업로드\' API(POST /upload-image)를 통해 얻은 이미지 URL을 전달하여 업데이트합니다.
         * @summary 프로필 이미지 업데이트
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProfileImage(file?: File, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.updateProfileImage(file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationUpdateInfoApi - object-oriented interface
 * @export
 * @class AuthenticationUpdateInfoApi
 * @extends {BaseAPI}
 */
export class AuthenticationUpdateInfoApi extends BaseAPI {
    /**
     * 인증된 사용자가 자신의 닉네임을 변경합니다. 새로운 닉네임은 다른 사용자가 사용하고 있지 않은 고유한 값이어야 합니다. 변경 전 \'닉네임 중복 검사\' API(GET /auth/check-nickname)를 통해 사용 가능 여부를 확인할 수 있습니다.
     * @summary 닉네임 변경
     * @param {ChangeNicknameRequest} [changeNicknameRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationUpdateInfoApi
     */
    public changeNickname(changeNicknameRequest?: ChangeNicknameRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationUpdateInfoApiFp(this.configuration).changeNickname(changeNicknameRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 인증된 사용자가 자신의 계정 비밀번호를 변경합니다. 보안을 위해, 이 API를 호출하기 전에 먼저 \'비밀번호 확인\' API(POST /auth/check-password)를 통해 사용자 인증을 완료하는 것을 권장합니다.
     * @summary 비밀번호 변경
     * @param {ChangePasswordRequest} [changePasswordRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationUpdateInfoApi
     */
    public changePassword(changePasswordRequest?: ChangePasswordRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationUpdateInfoApiFp(this.configuration).changePassword(changePasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 사용자가 비밀번호 변경 등 민감한 작업을 수행하기 전에, 현재 로그인된 계정의 소유주가 맞는지 확인하기 위해 현재 비밀번호를 입력받아 검증합니다. 인증된 사용자만 호출할 수 있습니다.
     * @summary 비밀번호 확인
     * @param {CheckPasswordRequest} [checkPasswordRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationUpdateInfoApi
     */
    public checkPassword(checkPasswordRequest?: CheckPasswordRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationUpdateInfoApiFp(this.configuration).checkPassword(checkPasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 인증된 사용자가 자신의 프로필 페이지에 표시될 소개글(bio)을 수정합니다. 최대 500자까지 입력할 수 있습니다.
     * @summary 소개글 업데이트
     * @param {UpdateBioRequest} [updateBioRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationUpdateInfoApi
     */
    public updateBio(updateBioRequest?: UpdateBioRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationUpdateInfoApiFp(this.configuration).updateBio(updateBioRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 인증된 사용자가 자신의 프로필 이미지를 변경합니다. 이미지 파일 자체를 업로드하는 것이 아니라, \'이미지 업로드\' API(POST /upload-image)를 통해 얻은 이미지 URL을 전달하여 업데이트합니다.
     * @summary 프로필 이미지 업데이트
     * @param {File} [file] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationUpdateInfoApi
     */
    public updateProfileImage(file?: File, options?: RawAxiosRequestConfig) {
        return AuthenticationUpdateInfoApiFp(this.configuration).updateProfileImage(file, options).then((request) => request(this.axios, this.basePath));
    }
}

