/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateComment200Response } from '../models';
// @ts-ignore
import type { CreateCommentRequest } from '../models';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { GetMyCollections200Response } from '../models';
// @ts-ignore
import type { SuccessResponse } from '../models';
// @ts-ignore
import type { ToggleCommentLike200Response } from '../models';
// @ts-ignore
import type { UpdateComment200Response } from '../models';
// @ts-ignore
import type { UpdateCommentRequest } from '../models';
/**
 * CommentsApi - axios parameter creator
 * @export
 */
export const CommentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 리뷰 또는 컬렉션에 새로운 댓글을 작성합니다. `parentId`를 포함하면 특정 댓글에 대한 답글(대댓글)로 작성됩니다. `parentId`가 없으면 일반 댓글로 작성됩니다.
         * @summary 댓글 작성
         * @param {CreateCommentRequest} [createCommentRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createComment: async (createCommentRequest?: CreateCommentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/comments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCommentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 리뷰 또는 컬렉션에 새로운 댓글을 작성합니다. `parentId`를 포함하면 특정 댓글에 대한 답글(대댓글)로 작성됩니다. `parentId`가 없으면 일반 댓글로 작성됩니다.
         * @summary 댓글 작성
         * @param {CreateCommentRequest} [createCommentRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createComment_1: async (createCommentRequest?: CreateCommentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/comments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCommentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 자신이 작성한 댓글을 삭제합니다. 다른 사용자의 댓글을 삭제하려고 할 경우 403 Forbidden 에러가 발생합니다.
         * @summary 댓글 삭제
         * @param {string} commentId 삭제할 댓글 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteComment: async (commentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'commentId' is not null or undefined
            assertParamExists('deleteComment', 'commentId', commentId)
            const localVarPath = `/comments/{commentId}`
                .replace(`{${"commentId"}}`, encodeURIComponent(String(commentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 자신이 작성한 댓글을 삭제합니다. 다른 사용자의 댓글을 삭제하려고 할 경우 403 Forbidden 에러가 발생합니다.
         * @summary 댓글 삭제
         * @param {string} commentId 삭제할 댓글 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteComment_2: async (commentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'commentId' is not null or undefined
            assertParamExists('deleteComment_2', 'commentId', commentId)
            const localVarPath = `/comments/{commentId}`
                .replace(`{${"commentId"}}`, encodeURIComponent(String(commentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * itemId의 댓글 상세 목록을 조회한다 리뷰 혹은 컬렉션에 댓글을 달 수 있으므로, type = \'review\' or \'collection\' sortBy option도 있슴
         * @summary 댓글 목록조회
         * @param {number} itemId 리뷰 or 콜렉션의 id
         * @param {GetMyCollectionsTypeEnum} [type] review or collection
         * @param {GetMyCollectionsSortByEnum} [sortBy] \&#39;likes\&#39; or \&#39;recent\&#39; or \&#39;old\&#39;/ default &#x3D; \&#39;recent\&#39;
         * @param {number} [page] 페이지 번호(1부터 시작)
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyCollections: async (itemId: number, type?: GetMyCollectionsTypeEnum, sortBy?: GetMyCollectionsSortByEnum, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'itemId' is not null or undefined
            assertParamExists('getMyCollections', 'itemId', itemId)
            const localVarPath = `/comments/detail/{itemId}`
                .replace(`{${"itemId"}}`, encodeURIComponent(String(itemId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 댓글에 대한 \'좋아요\' 상태를 변경(토글)합니다. 사용자가 해당 댓글에 좋아요를 누르지 않은 상태이면 좋아요를 추가하고, 이미 누른 상태이면 좋아요를 취소합니다.
         * @summary 댓글 좋아요 토글
         * @param {string} commentId 좋아요를 토글할 댓글 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        toggleCommentLike: async (commentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'commentId' is not null or undefined
            assertParamExists('toggleCommentLike', 'commentId', commentId)
            const localVarPath = `/comments/{commentId}/like`
                .replace(`{${"commentId"}}`, encodeURIComponent(String(commentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 댓글에 대한 \'좋아요\' 상태를 변경(토글)합니다. 사용자가 해당 댓글에 좋아요를 누르지 않은 상태이면 좋아요를 추가하고, 이미 누른 상태이면 좋아요를 취소합니다.
         * @summary 댓글 좋아요 토글
         * @param {string} commentId 좋아요를 토글할 댓글 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        toggleCommentLike_3: async (commentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'commentId' is not null or undefined
            assertParamExists('toggleCommentLike_3', 'commentId', commentId)
            const localVarPath = `/comments/{commentId}/like`
                .replace(`{${"commentId"}}`, encodeURIComponent(String(commentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 자신이 작성한 댓글의 내용을 수정합니다. 다른 사용자의 댓글을 수정하려고 할 경우 403 Forbidden 에러가 발생합니다.
         * @summary 댓글 수정
         * @param {number} commentId 수정할 댓글 ID
         * @param {UpdateCommentRequest} [updateCommentRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateComment: async (commentId: number, updateCommentRequest?: UpdateCommentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'commentId' is not null or undefined
            assertParamExists('updateComment', 'commentId', commentId)
            const localVarPath = `/comments/{commentId}`
                .replace(`{${"commentId"}}`, encodeURIComponent(String(commentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCommentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 자신이 작성한 댓글의 내용을 수정합니다. 다른 사용자의 댓글을 수정하려고 할 경우 403 Forbidden 에러가 발생합니다.
         * @summary 댓글 수정
         * @param {number} commentId 수정할 댓글 ID
         * @param {UpdateCommentRequest} [updateCommentRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateComment_4: async (commentId: number, updateCommentRequest?: UpdateCommentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'commentId' is not null or undefined
            assertParamExists('updateComment_4', 'commentId', commentId)
            const localVarPath = `/comments/{commentId}`
                .replace(`{${"commentId"}}`, encodeURIComponent(String(commentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCommentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CommentsApi - functional programming interface
 * @export
 */
export const CommentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CommentsApiAxiosParamCreator(configuration)
    return {
        /**
         * 리뷰 또는 컬렉션에 새로운 댓글을 작성합니다. `parentId`를 포함하면 특정 댓글에 대한 답글(대댓글)로 작성됩니다. `parentId`가 없으면 일반 댓글로 작성됩니다.
         * @summary 댓글 작성
         * @param {CreateCommentRequest} [createCommentRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createComment(createCommentRequest?: CreateCommentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateComment200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createComment(createCommentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.createComment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 리뷰 또는 컬렉션에 새로운 댓글을 작성합니다. `parentId`를 포함하면 특정 댓글에 대한 답글(대댓글)로 작성됩니다. `parentId`가 없으면 일반 댓글로 작성됩니다.
         * @summary 댓글 작성
         * @param {CreateCommentRequest} [createCommentRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createComment_1(createCommentRequest?: CreateCommentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateComment200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createComment_1(createCommentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.createComment_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 자신이 작성한 댓글을 삭제합니다. 다른 사용자의 댓글을 삭제하려고 할 경우 403 Forbidden 에러가 발생합니다.
         * @summary 댓글 삭제
         * @param {string} commentId 삭제할 댓글 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteComment(commentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteComment(commentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.deleteComment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 자신이 작성한 댓글을 삭제합니다. 다른 사용자의 댓글을 삭제하려고 할 경우 403 Forbidden 에러가 발생합니다.
         * @summary 댓글 삭제
         * @param {string} commentId 삭제할 댓글 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteComment_2(commentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SuccessResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteComment_2(commentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.deleteComment_2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * itemId의 댓글 상세 목록을 조회한다 리뷰 혹은 컬렉션에 댓글을 달 수 있으므로, type = \'review\' or \'collection\' sortBy option도 있슴
         * @summary 댓글 목록조회
         * @param {number} itemId 리뷰 or 콜렉션의 id
         * @param {GetMyCollectionsTypeEnum} [type] review or collection
         * @param {GetMyCollectionsSortByEnum} [sortBy] \&#39;likes\&#39; or \&#39;recent\&#39; or \&#39;old\&#39;/ default &#x3D; \&#39;recent\&#39;
         * @param {number} [page] 페이지 번호(1부터 시작)
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyCollections(itemId: number, type?: GetMyCollectionsTypeEnum, sortBy?: GetMyCollectionsSortByEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMyCollections200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyCollections(itemId, type, sortBy, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.getMyCollections']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 댓글에 대한 \'좋아요\' 상태를 변경(토글)합니다. 사용자가 해당 댓글에 좋아요를 누르지 않은 상태이면 좋아요를 추가하고, 이미 누른 상태이면 좋아요를 취소합니다.
         * @summary 댓글 좋아요 토글
         * @param {string} commentId 좋아요를 토글할 댓글 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async toggleCommentLike(commentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ToggleCommentLike200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.toggleCommentLike(commentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.toggleCommentLike']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 댓글에 대한 \'좋아요\' 상태를 변경(토글)합니다. 사용자가 해당 댓글에 좋아요를 누르지 않은 상태이면 좋아요를 추가하고, 이미 누른 상태이면 좋아요를 취소합니다.
         * @summary 댓글 좋아요 토글
         * @param {string} commentId 좋아요를 토글할 댓글 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async toggleCommentLike_3(commentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ToggleCommentLike200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.toggleCommentLike_3(commentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.toggleCommentLike_3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 자신이 작성한 댓글의 내용을 수정합니다. 다른 사용자의 댓글을 수정하려고 할 경우 403 Forbidden 에러가 발생합니다.
         * @summary 댓글 수정
         * @param {number} commentId 수정할 댓글 ID
         * @param {UpdateCommentRequest} [updateCommentRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateComment(commentId: number, updateCommentRequest?: UpdateCommentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateComment200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateComment(commentId, updateCommentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.updateComment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 자신이 작성한 댓글의 내용을 수정합니다. 다른 사용자의 댓글을 수정하려고 할 경우 403 Forbidden 에러가 발생합니다.
         * @summary 댓글 수정
         * @param {number} commentId 수정할 댓글 ID
         * @param {UpdateCommentRequest} [updateCommentRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateComment_4(commentId: number, updateCommentRequest?: UpdateCommentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateComment200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateComment_4(commentId, updateCommentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.updateComment_4']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CommentsApi - factory interface
 * @export
 */
export const CommentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CommentsApiFp(configuration)
    return {
        /**
         * 리뷰 또는 컬렉션에 새로운 댓글을 작성합니다. `parentId`를 포함하면 특정 댓글에 대한 답글(대댓글)로 작성됩니다. `parentId`가 없으면 일반 댓글로 작성됩니다.
         * @summary 댓글 작성
         * @param {CreateCommentRequest} [createCommentRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createComment(createCommentRequest?: CreateCommentRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateComment200Response> {
            return localVarFp.createComment(createCommentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 리뷰 또는 컬렉션에 새로운 댓글을 작성합니다. `parentId`를 포함하면 특정 댓글에 대한 답글(대댓글)로 작성됩니다. `parentId`가 없으면 일반 댓글로 작성됩니다.
         * @summary 댓글 작성
         * @param {CreateCommentRequest} [createCommentRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createComment_1(createCommentRequest?: CreateCommentRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateComment200Response> {
            return localVarFp.createComment_1(createCommentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 자신이 작성한 댓글을 삭제합니다. 다른 사용자의 댓글을 삭제하려고 할 경우 403 Forbidden 에러가 발생합니다.
         * @summary 댓글 삭제
         * @param {string} commentId 삭제할 댓글 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteComment(commentId: string, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.deleteComment(commentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 자신이 작성한 댓글을 삭제합니다. 다른 사용자의 댓글을 삭제하려고 할 경우 403 Forbidden 에러가 발생합니다.
         * @summary 댓글 삭제
         * @param {string} commentId 삭제할 댓글 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteComment_2(commentId: string, options?: RawAxiosRequestConfig): AxiosPromise<SuccessResponse> {
            return localVarFp.deleteComment_2(commentId, options).then((request) => request(axios, basePath));
        },
        /**
         * itemId의 댓글 상세 목록을 조회한다 리뷰 혹은 컬렉션에 댓글을 달 수 있으므로, type = \'review\' or \'collection\' sortBy option도 있슴
         * @summary 댓글 목록조회
         * @param {number} itemId 리뷰 or 콜렉션의 id
         * @param {GetMyCollectionsTypeEnum} [type] review or collection
         * @param {GetMyCollectionsSortByEnum} [sortBy] \&#39;likes\&#39; or \&#39;recent\&#39; or \&#39;old\&#39;/ default &#x3D; \&#39;recent\&#39;
         * @param {number} [page] 페이지 번호(1부터 시작)
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyCollections(itemId: number, type?: GetMyCollectionsTypeEnum, sortBy?: GetMyCollectionsSortByEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetMyCollections200Response> {
            return localVarFp.getMyCollections(itemId, type, sortBy, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 댓글에 대한 \'좋아요\' 상태를 변경(토글)합니다. 사용자가 해당 댓글에 좋아요를 누르지 않은 상태이면 좋아요를 추가하고, 이미 누른 상태이면 좋아요를 취소합니다.
         * @summary 댓글 좋아요 토글
         * @param {string} commentId 좋아요를 토글할 댓글 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        toggleCommentLike(commentId: string, options?: RawAxiosRequestConfig): AxiosPromise<ToggleCommentLike200Response> {
            return localVarFp.toggleCommentLike(commentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 댓글에 대한 \'좋아요\' 상태를 변경(토글)합니다. 사용자가 해당 댓글에 좋아요를 누르지 않은 상태이면 좋아요를 추가하고, 이미 누른 상태이면 좋아요를 취소합니다.
         * @summary 댓글 좋아요 토글
         * @param {string} commentId 좋아요를 토글할 댓글 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        toggleCommentLike_3(commentId: string, options?: RawAxiosRequestConfig): AxiosPromise<ToggleCommentLike200Response> {
            return localVarFp.toggleCommentLike_3(commentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 자신이 작성한 댓글의 내용을 수정합니다. 다른 사용자의 댓글을 수정하려고 할 경우 403 Forbidden 에러가 발생합니다.
         * @summary 댓글 수정
         * @param {number} commentId 수정할 댓글 ID
         * @param {UpdateCommentRequest} [updateCommentRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateComment(commentId: number, updateCommentRequest?: UpdateCommentRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpdateComment200Response> {
            return localVarFp.updateComment(commentId, updateCommentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 자신이 작성한 댓글의 내용을 수정합니다. 다른 사용자의 댓글을 수정하려고 할 경우 403 Forbidden 에러가 발생합니다.
         * @summary 댓글 수정
         * @param {number} commentId 수정할 댓글 ID
         * @param {UpdateCommentRequest} [updateCommentRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateComment_4(commentId: number, updateCommentRequest?: UpdateCommentRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpdateComment200Response> {
            return localVarFp.updateComment_4(commentId, updateCommentRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CommentsApi - object-oriented interface
 * @export
 * @class CommentsApi
 * @extends {BaseAPI}
 */
export class CommentsApi extends BaseAPI {
    /**
     * 리뷰 또는 컬렉션에 새로운 댓글을 작성합니다. `parentId`를 포함하면 특정 댓글에 대한 답글(대댓글)로 작성됩니다. `parentId`가 없으면 일반 댓글로 작성됩니다.
     * @summary 댓글 작성
     * @param {CreateCommentRequest} [createCommentRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommentsApi
     */
    public createComment(createCommentRequest?: CreateCommentRequest, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).createComment(createCommentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 리뷰 또는 컬렉션에 새로운 댓글을 작성합니다. `parentId`를 포함하면 특정 댓글에 대한 답글(대댓글)로 작성됩니다. `parentId`가 없으면 일반 댓글로 작성됩니다.
     * @summary 댓글 작성
     * @param {CreateCommentRequest} [createCommentRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommentsApi
     */
    public createComment_1(createCommentRequest?: CreateCommentRequest, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).createComment_1(createCommentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 자신이 작성한 댓글을 삭제합니다. 다른 사용자의 댓글을 삭제하려고 할 경우 403 Forbidden 에러가 발생합니다.
     * @summary 댓글 삭제
     * @param {string} commentId 삭제할 댓글 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommentsApi
     */
    public deleteComment(commentId: string, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).deleteComment(commentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 자신이 작성한 댓글을 삭제합니다. 다른 사용자의 댓글을 삭제하려고 할 경우 403 Forbidden 에러가 발생합니다.
     * @summary 댓글 삭제
     * @param {string} commentId 삭제할 댓글 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommentsApi
     */
    public deleteComment_2(commentId: string, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).deleteComment_2(commentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * itemId의 댓글 상세 목록을 조회한다 리뷰 혹은 컬렉션에 댓글을 달 수 있으므로, type = \'review\' or \'collection\' sortBy option도 있슴
     * @summary 댓글 목록조회
     * @param {number} itemId 리뷰 or 콜렉션의 id
     * @param {GetMyCollectionsTypeEnum} [type] review or collection
     * @param {GetMyCollectionsSortByEnum} [sortBy] \&#39;likes\&#39; or \&#39;recent\&#39; or \&#39;old\&#39;/ default &#x3D; \&#39;recent\&#39;
     * @param {number} [page] 페이지 번호(1부터 시작)
     * @param {number} [limit] 페이지당 항목 수
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommentsApi
     */
    public getMyCollections(itemId: number, type?: GetMyCollectionsTypeEnum, sortBy?: GetMyCollectionsSortByEnum, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).getMyCollections(itemId, type, sortBy, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 댓글에 대한 \'좋아요\' 상태를 변경(토글)합니다. 사용자가 해당 댓글에 좋아요를 누르지 않은 상태이면 좋아요를 추가하고, 이미 누른 상태이면 좋아요를 취소합니다.
     * @summary 댓글 좋아요 토글
     * @param {string} commentId 좋아요를 토글할 댓글 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommentsApi
     */
    public toggleCommentLike(commentId: string, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).toggleCommentLike(commentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 댓글에 대한 \'좋아요\' 상태를 변경(토글)합니다. 사용자가 해당 댓글에 좋아요를 누르지 않은 상태이면 좋아요를 추가하고, 이미 누른 상태이면 좋아요를 취소합니다.
     * @summary 댓글 좋아요 토글
     * @param {string} commentId 좋아요를 토글할 댓글 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommentsApi
     */
    public toggleCommentLike_3(commentId: string, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).toggleCommentLike_3(commentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 자신이 작성한 댓글의 내용을 수정합니다. 다른 사용자의 댓글을 수정하려고 할 경우 403 Forbidden 에러가 발생합니다.
     * @summary 댓글 수정
     * @param {number} commentId 수정할 댓글 ID
     * @param {UpdateCommentRequest} [updateCommentRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommentsApi
     */
    public updateComment(commentId: number, updateCommentRequest?: UpdateCommentRequest, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).updateComment(commentId, updateCommentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 자신이 작성한 댓글의 내용을 수정합니다. 다른 사용자의 댓글을 수정하려고 할 경우 403 Forbidden 에러가 발생합니다.
     * @summary 댓글 수정
     * @param {number} commentId 수정할 댓글 ID
     * @param {UpdateCommentRequest} [updateCommentRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CommentsApi
     */
    public updateComment_4(commentId: number, updateCommentRequest?: UpdateCommentRequest, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).updateComment_4(commentId, updateCommentRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetMyCollectionsTypeEnum = {
    Collection: 'collection',
    Review: 'review'
} as const;
export type GetMyCollectionsTypeEnum = typeof GetMyCollectionsTypeEnum[keyof typeof GetMyCollectionsTypeEnum];
/**
 * @export
 */
export const GetMyCollectionsSortByEnum = {
    Recent: 'recent',
    Old: 'old',
    Popularity: 'popularity'
} as const;
export type GetMyCollectionsSortByEnum = typeof GetMyCollectionsSortByEnum[keyof typeof GetMyCollectionsSortByEnum];
