/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { RecommendGet200Response } from '../models';
// @ts-ignore
import type { UpdatePreferenceFromArtistLikePost401Response } from '../models';
// @ts-ignore
import type { UpdatePreferencePost200Response } from '../models';
/**
 * FastAPIApi - axios parameter creator
 * @export
 */
export const FastAPIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 맞춤 컬렉션 추천 조회
         * @param {number} [userId] 유저 아이디
         * @param {string} [topK] 추천 개수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendGet: async (userId?: number, topK?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/recommend`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (topK !== undefined) {
                localVarQueryParameter['top_k'] = topK;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 아티스트 좋아요로 선호도 업데이트
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePreferenceFromArtistLikePost: async (body?: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/update_preference_from_artist_like`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 선호도 업데이트
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePreferencePost: async (body?: object, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/update_preference`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FastAPIApi - functional programming interface
 * @export
 */
export const FastAPIApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FastAPIApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 맞춤 컬렉션 추천 조회
         * @param {number} [userId] 유저 아이디
         * @param {string} [topK] 추천 개수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recommendGet(userId?: number, topK?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecommendGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recommendGet(userId, topK, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FastAPIApi.recommendGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 아티스트 좋아요로 선호도 업데이트
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePreferenceFromArtistLikePost(body?: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePreferenceFromArtistLikePost(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FastAPIApi.updatePreferenceFromArtistLikePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 선호도 업데이트
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePreferencePost(body?: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdatePreferencePost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePreferencePost(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FastAPIApi.updatePreferencePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FastAPIApi - factory interface
 * @export
 */
export const FastAPIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FastAPIApiFp(configuration)
    return {
        /**
         * 
         * @summary 맞춤 컬렉션 추천 조회
         * @param {number} [userId] 유저 아이디
         * @param {string} [topK] 추천 개수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recommendGet(userId?: number, topK?: string, options?: RawAxiosRequestConfig): AxiosPromise<RecommendGet200Response> {
            return localVarFp.recommendGet(userId, topK, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 아티스트 좋아요로 선호도 업데이트
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePreferenceFromArtistLikePost(body?: object, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updatePreferenceFromArtistLikePost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 선호도 업데이트
         * @param {object} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePreferencePost(body?: object, options?: RawAxiosRequestConfig): AxiosPromise<UpdatePreferencePost200Response> {
            return localVarFp.updatePreferencePost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FastAPIApi - object-oriented interface
 * @export
 * @class FastAPIApi
 * @extends {BaseAPI}
 */
export class FastAPIApi extends BaseAPI {
    /**
     * 
     * @summary 맞춤 컬렉션 추천 조회
     * @param {number} [userId] 유저 아이디
     * @param {string} [topK] 추천 개수
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FastAPIApi
     */
    public recommendGet(userId?: number, topK?: string, options?: RawAxiosRequestConfig) {
        return FastAPIApiFp(this.configuration).recommendGet(userId, topK, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 아티스트 좋아요로 선호도 업데이트
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FastAPIApi
     */
    public updatePreferenceFromArtistLikePost(body?: object, options?: RawAxiosRequestConfig) {
        return FastAPIApiFp(this.configuration).updatePreferenceFromArtistLikePost(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 선호도 업데이트
     * @param {object} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FastAPIApi
     */
    public updatePreferencePost(body?: object, options?: RawAxiosRequestConfig) {
        return FastAPIApiFp(this.configuration).updatePreferencePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}

