/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { Search200Response } from '../models';
// @ts-ignore
import type { Search200Response1 } from '../models';
/**
 * SearchApi - axios parameter creator
 * @export
 */
export const SearchApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 키워드를 사용하여 앨범, 트랙, 아티스트를 통합 검색합니다. `type` 파라미터를 통해 검색 범위를 \'all\'(전체), \'album\', \'track\', \'artist\' 중 하나로 지정할 수 있습니다. 현재 검색어는 영어만 지원하며, 띄어쓰기 없이 입력해야 합니다.
         * @summary 컬렉션 검색
         * @param {string} [q] 이름 
         * @param {string} [sortBy] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search: async (q?: string, sortBy?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/collections/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 키워드를 사용하여 앨범, 트랙, 아티스트를 통합 검색합니다. `type` 파라미터를 통해 검색 범위를 \'all\'(전체), \'album\', \'track\', \'artist\' 중 하나로 지정할 수 있습니다. 현재 검색어는 영어만 지원하며, 띄어쓰기 없이 입력해야 합니다.
         * @summary 통합 검색
         * @param {string} query 검색어 (영어, 띄어쓰기 불가)
         * @param {Search0TypeEnum} type 검색 타입 (all: 전체, album: 앨범만, track: 트랙만, artist: 아티스트만)
         * @param {string} [authorization] 선택사항. 로그인 시 사용자별 평가 상태 등 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search_1: async (query: string, type: Search0TypeEnum, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'query' is not null or undefined
            assertParamExists('search_1', 'query', query)
            // verify required parameter 'type' is not null or undefined
            assertParamExists('search_1', 'type', type)
            const localVarPath = `/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 키워드를 사용하여 앨범, 트랙, 아티스트를 통합 검색합니다. `type` 파라미터를 통해 검색 범위를 \'all\'(전체), \'album\', \'track\', \'artist\' 중 하나로 지정할 수 있습니다. 현재 검색어는 영어만 지원하며, 띄어쓰기 없이 입력해야 합니다.
         * @summary 통합 검색
         * @param {string} query 검색어 (영어, 띄어쓰기 불가)
         * @param {Search1TypeEnum} type 검색 타입 (all: 전체, album: 앨범만, track: 트랙만, artist: 아티스트만)
         * @param {string} [authorization] 선택사항. 로그인 시 사용자별 평가 상태 등 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search_2: async (query: string, type: Search1TypeEnum, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'query' is not null or undefined
            assertParamExists('search_2', 'query', query)
            // verify required parameter 'type' is not null or undefined
            assertParamExists('search_2', 'type', type)
            const localVarPath = `/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SearchApi - functional programming interface
 * @export
 */
export const SearchApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SearchApiAxiosParamCreator(configuration)
    return {
        /**
         * 키워드를 사용하여 앨범, 트랙, 아티스트를 통합 검색합니다. `type` 파라미터를 통해 검색 범위를 \'all\'(전체), \'album\', \'track\', \'artist\' 중 하나로 지정할 수 있습니다. 현재 검색어는 영어만 지원하며, 띄어쓰기 없이 입력해야 합니다.
         * @summary 컬렉션 검색
         * @param {string} [q] 이름 
         * @param {string} [sortBy] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async search(q?: string, sortBy?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Search200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.search(q, sortBy, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SearchApi.search']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 키워드를 사용하여 앨범, 트랙, 아티스트를 통합 검색합니다. `type` 파라미터를 통해 검색 범위를 \'all\'(전체), \'album\', \'track\', \'artist\' 중 하나로 지정할 수 있습니다. 현재 검색어는 영어만 지원하며, 띄어쓰기 없이 입력해야 합니다.
         * @summary 통합 검색
         * @param {string} query 검색어 (영어, 띄어쓰기 불가)
         * @param {Search0TypeEnum} type 검색 타입 (all: 전체, album: 앨범만, track: 트랙만, artist: 아티스트만)
         * @param {string} [authorization] 선택사항. 로그인 시 사용자별 평가 상태 등 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async search_1(query: string, type: Search0TypeEnum, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Search200Response1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.search_1(query, type, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SearchApi.search_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 키워드를 사용하여 앨범, 트랙, 아티스트를 통합 검색합니다. `type` 파라미터를 통해 검색 범위를 \'all\'(전체), \'album\', \'track\', \'artist\' 중 하나로 지정할 수 있습니다. 현재 검색어는 영어만 지원하며, 띄어쓰기 없이 입력해야 합니다.
         * @summary 통합 검색
         * @param {string} query 검색어 (영어, 띄어쓰기 불가)
         * @param {Search1TypeEnum} type 검색 타입 (all: 전체, album: 앨범만, track: 트랙만, artist: 아티스트만)
         * @param {string} [authorization] 선택사항. 로그인 시 사용자별 평가 상태 등 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async search_2(query: string, type: Search1TypeEnum, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Search200Response1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.search_2(query, type, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SearchApi.search_2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SearchApi - factory interface
 * @export
 */
export const SearchApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SearchApiFp(configuration)
    return {
        /**
         * 키워드를 사용하여 앨범, 트랙, 아티스트를 통합 검색합니다. `type` 파라미터를 통해 검색 범위를 \'all\'(전체), \'album\', \'track\', \'artist\' 중 하나로 지정할 수 있습니다. 현재 검색어는 영어만 지원하며, 띄어쓰기 없이 입력해야 합니다.
         * @summary 컬렉션 검색
         * @param {string} [q] 이름 
         * @param {string} [sortBy] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search(q?: string, sortBy?: string, options?: RawAxiosRequestConfig): AxiosPromise<Search200Response> {
            return localVarFp.search(q, sortBy, options).then((request) => request(axios, basePath));
        },
        /**
         * 키워드를 사용하여 앨범, 트랙, 아티스트를 통합 검색합니다. `type` 파라미터를 통해 검색 범위를 \'all\'(전체), \'album\', \'track\', \'artist\' 중 하나로 지정할 수 있습니다. 현재 검색어는 영어만 지원하며, 띄어쓰기 없이 입력해야 합니다.
         * @summary 통합 검색
         * @param {string} query 검색어 (영어, 띄어쓰기 불가)
         * @param {Search0TypeEnum} type 검색 타입 (all: 전체, album: 앨범만, track: 트랙만, artist: 아티스트만)
         * @param {string} [authorization] 선택사항. 로그인 시 사용자별 평가 상태 등 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search_1(query: string, type: Search0TypeEnum, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<Search200Response1> {
            return localVarFp.search_1(query, type, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 키워드를 사용하여 앨범, 트랙, 아티스트를 통합 검색합니다. `type` 파라미터를 통해 검색 범위를 \'all\'(전체), \'album\', \'track\', \'artist\' 중 하나로 지정할 수 있습니다. 현재 검색어는 영어만 지원하며, 띄어쓰기 없이 입력해야 합니다.
         * @summary 통합 검색
         * @param {string} query 검색어 (영어, 띄어쓰기 불가)
         * @param {Search1TypeEnum} type 검색 타입 (all: 전체, album: 앨범만, track: 트랙만, artist: 아티스트만)
         * @param {string} [authorization] 선택사항. 로그인 시 사용자별 평가 상태 등 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        search_2(query: string, type: Search1TypeEnum, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<Search200Response1> {
            return localVarFp.search_2(query, type, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SearchApi - object-oriented interface
 * @export
 * @class SearchApi
 * @extends {BaseAPI}
 */
export class SearchApi extends BaseAPI {
    /**
     * 키워드를 사용하여 앨범, 트랙, 아티스트를 통합 검색합니다. `type` 파라미터를 통해 검색 범위를 \'all\'(전체), \'album\', \'track\', \'artist\' 중 하나로 지정할 수 있습니다. 현재 검색어는 영어만 지원하며, 띄어쓰기 없이 입력해야 합니다.
     * @summary 컬렉션 검색
     * @param {string} [q] 이름 
     * @param {string} [sortBy] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApi
     */
    public search(q?: string, sortBy?: string, options?: RawAxiosRequestConfig) {
        return SearchApiFp(this.configuration).search(q, sortBy, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 키워드를 사용하여 앨범, 트랙, 아티스트를 통합 검색합니다. `type` 파라미터를 통해 검색 범위를 \'all\'(전체), \'album\', \'track\', \'artist\' 중 하나로 지정할 수 있습니다. 현재 검색어는 영어만 지원하며, 띄어쓰기 없이 입력해야 합니다.
     * @summary 통합 검색
     * @param {string} query 검색어 (영어, 띄어쓰기 불가)
     * @param {Search0TypeEnum} type 검색 타입 (all: 전체, album: 앨범만, track: 트랙만, artist: 아티스트만)
     * @param {string} [authorization] 선택사항. 로그인 시 사용자별 평가 상태 등 추가 정보 제공
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApi
     */
    public search_1(query: string, type: Search0TypeEnum, authorization?: string, options?: RawAxiosRequestConfig) {
        return SearchApiFp(this.configuration).search_1(query, type, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 키워드를 사용하여 앨범, 트랙, 아티스트를 통합 검색합니다. `type` 파라미터를 통해 검색 범위를 \'all\'(전체), \'album\', \'track\', \'artist\' 중 하나로 지정할 수 있습니다. 현재 검색어는 영어만 지원하며, 띄어쓰기 없이 입력해야 합니다.
     * @summary 통합 검색
     * @param {string} query 검색어 (영어, 띄어쓰기 불가)
     * @param {Search1TypeEnum} type 검색 타입 (all: 전체, album: 앨범만, track: 트랙만, artist: 아티스트만)
     * @param {string} [authorization] 선택사항. 로그인 시 사용자별 평가 상태 등 추가 정보 제공
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApi
     */
    public search_2(query: string, type: Search1TypeEnum, authorization?: string, options?: RawAxiosRequestConfig) {
        return SearchApiFp(this.configuration).search_2(query, type, authorization, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const Search0TypeEnum = {
    All: 'all',
    Album: 'album',
    Track: 'track',
    Artist: 'artist'
} as const;
export type Search0TypeEnum = typeof Search0TypeEnum[keyof typeof Search0TypeEnum];
/**
 * @export
 */
export const Search1TypeEnum = {
    All: 'all',
    Album: 'album',
    Track: 'track',
    Artist: 'artist'
} as const;
export type Search1TypeEnum = typeof Search1TypeEnum[keyof typeof Search1TypeEnum];
