/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { GetLikedArtists200Response } from '../models';
// @ts-ignore
import type { GetMyActivity200Response } from '../models';
// @ts-ignore
import type { GetMyCollections200Response } from '../models';
// @ts-ignore
import type { GetRatedAlbums200Response } from '../models';
// @ts-ignore
import type { GetRatedTracks200Response } from '../models';
// @ts-ignore
import type { GetUserCollections200Response } from '../models';
// @ts-ignore
import type { GetUserCollections200Response1 } from '../models';
// @ts-ignore
import type { GetUserCollections200Response2 } from '../models';
// @ts-ignore
import type { GetUserCollections200Response3 } from '../models';
// @ts-ignore
import type { GetUserCollectionsRequest } from '../models';
// @ts-ignore
import type { GetUserRateRecords200Response } from '../models';
// @ts-ignore
import type { GetUserRatedAlbums200Response } from '../models';
// @ts-ignore
import type { GetUserRatedTracks200Response } from '../models';
/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
         * @summary 좋아요한 아티스트 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLikedArtists: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/liked-artist`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
         * @summary 좋아요한 아티스트 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLikedArtists_1: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/liked-artist`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
         * @summary 내 활동 페이지 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyActivity: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/activity`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
         * @summary 내 활동 페이지 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyActivity_2: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/activity`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 인증된 사용자가 생성한 모든 컬렉션의 목록을 조회합니다. 여기에는 공개(public) 및 비공개(private) 컬렉션이 모두 포함됩니다.
         * @summary 내 컬렉션 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyCollections: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/collections`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 인증된 사용자가 생성한 모든 컬렉션의 목록을 조회합니다. 여기에는 공개(public) 및 비공개(private) 컬렉션이 모두 포함됩니다.
         * @summary 좋아요한 컬렉션 목록
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyCollections_3: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getMyCollections_3', 'userId', userId)
            const localVarPath = `/users/{userId}/collections/liked`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
         * @summary 리뷰(내용 있는) 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRatedAlbums: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/review-list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
         * @summary 리뷰(내용 있는) 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRatedAlbums_4: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/review-list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 인증된 사용자가 리뷰(평가)를 남긴 모든 트랙의 목록을 조회합니다.
         * @summary 평가한 트랙 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRatedTracks: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/track-rate-record`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 인증된 사용자가 리뷰(평가)를 남긴 모든 트랙의 목록을 조회합니다.
         * @summary 평가한 트랙 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRatedTracks_5: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/track-rate-record`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 내 칭호 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/badges`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 활성화된 칭호 확인
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections_6: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/active-badge`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 칭호 설정
         * @param {GetUserCollectionsRequest} [getUserCollectionsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections_7: async (getUserCollectionsRequest?: GetUserCollectionsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/active-badge`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(getUserCollectionsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 타인의 칭호 목록 조회
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections_8: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserCollections_8', 'userId', userId)
            const localVarPath = `/users/{userId}/badges`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자가 생성한 컬렉션 중 \'공개(public)\'로 설정된 목록만 조회합니다. 다른 사용자의 비공개 컬렉션은 이 API를 통해 조회할 수 없습니다.
         * @summary 타인의 컬렉션 목록 조회
         * @param {string} userId 조회할 사용자 ID (integer)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections_9: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserCollections_9', 'userId', userId)
            const localVarPath = `/users/{userId}/collections`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자의 전체 평가 기록 페이지 정보를 조회합니다. 사용자 프로필, 통계, 별점 분포, 컬렉션, 장르 키워드, 최근 평가한 앨범/트랙 정보를 포함합니다.
         * @summary 평가 기록 전체 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRateRecords: async (userId: string, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserRateRecords', 'userId', userId)
            const localVarPath = `/users/{userId}/rate-records`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자의 전체 평가 기록 페이지 정보를 조회합니다. 사용자 프로필, 통계, 별점 분포, 컬렉션, 장르 키워드, 최근 평가한 앨범/트랙 정보를 포함합니다.
         * @summary 평가 기록 전체 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRateRecords_10: async (userId: string, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserRateRecords_10', 'userId', userId)
            const localVarPath = `/users/{userId}/rate-records`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
         * @summary 평가한 앨범 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedAlbums: async (userId: string, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserRatedAlbums', 'userId', userId)
            const localVarPath = `/users/{userId}/rated-albums`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
         * @summary 평가한 앨범 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedAlbums_11: async (userId: string, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserRatedAlbums_11', 'userId', userId)
            const localVarPath = `/users/{userId}/rated-albums`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
         * @summary 평가한 트랙 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedTracks: async (userId: string, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserRatedTracks', 'userId', userId)
            const localVarPath = `/users/{userId}/rated-tracks`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
         * @summary 평가한 트랙 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedTracks_12: async (userId: string, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserRatedTracks_12', 'userId', userId)
            const localVarPath = `/users/{userId}/rated-tracks`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary /users/{userId}
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUserIdGet: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('usersUserIdGet', 'userId', userId)
            const localVarPath = `/users/{userId}`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
         * @summary 좋아요한 아티스트 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLikedArtists(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetLikedArtists200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLikedArtists(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getLikedArtists']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
         * @summary 좋아요한 아티스트 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLikedArtists_1(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetLikedArtists200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLikedArtists_1(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getLikedArtists_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
         * @summary 내 활동 페이지 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyActivity(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMyActivity200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyActivity(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getMyActivity']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
         * @summary 내 활동 페이지 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyActivity_2(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMyActivity200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyActivity_2(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getMyActivity_2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 인증된 사용자가 생성한 모든 컬렉션의 목록을 조회합니다. 여기에는 공개(public) 및 비공개(private) 컬렉션이 모두 포함됩니다.
         * @summary 내 컬렉션 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyCollections(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserCollections200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyCollections(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getMyCollections']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 인증된 사용자가 생성한 모든 컬렉션의 목록을 조회합니다. 여기에는 공개(public) 및 비공개(private) 컬렉션이 모두 포함됩니다.
         * @summary 좋아요한 컬렉션 목록
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyCollections_3(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMyCollections200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyCollections_3(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getMyCollections_3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
         * @summary 리뷰(내용 있는) 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRatedAlbums(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRatedAlbums200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRatedAlbums(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getRatedAlbums']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
         * @summary 리뷰(내용 있는) 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRatedAlbums_4(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRatedAlbums200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRatedAlbums_4(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getRatedAlbums_4']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 인증된 사용자가 리뷰(평가)를 남긴 모든 트랙의 목록을 조회합니다.
         * @summary 평가한 트랙 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRatedTracks(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRatedTracks200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRatedTracks(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getRatedTracks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 인증된 사용자가 리뷰(평가)를 남긴 모든 트랙의 목록을 조회합니다.
         * @summary 평가한 트랙 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRatedTracks_5(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRatedTracks200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRatedTracks_5(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getRatedTracks_5']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 내 칭호 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserCollections(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserCollections200Response1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserCollections(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserCollections']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 활성화된 칭호 확인
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserCollections_6(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserCollections200Response2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserCollections_6(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserCollections_6']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 칭호 설정
         * @param {GetUserCollectionsRequest} [getUserCollectionsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserCollections_7(getUserCollectionsRequest?: GetUserCollectionsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserCollections200Response3>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserCollections_7(getUserCollectionsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserCollections_7']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 타인의 칭호 목록 조회
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserCollections_8(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserCollections200Response1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserCollections_8(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserCollections_8']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자가 생성한 컬렉션 중 \'공개(public)\'로 설정된 목록만 조회합니다. 다른 사용자의 비공개 컬렉션은 이 API를 통해 조회할 수 없습니다.
         * @summary 타인의 컬렉션 목록 조회
         * @param {string} userId 조회할 사용자 ID (integer)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserCollections_9(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserCollections200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserCollections_9(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserCollections_9']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자의 전체 평가 기록 페이지 정보를 조회합니다. 사용자 프로필, 통계, 별점 분포, 컬렉션, 장르 키워드, 최근 평가한 앨범/트랙 정보를 포함합니다.
         * @summary 평가 기록 전체 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserRateRecords(userId: string, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserRateRecords200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserRateRecords(userId, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserRateRecords']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자의 전체 평가 기록 페이지 정보를 조회합니다. 사용자 프로필, 통계, 별점 분포, 컬렉션, 장르 키워드, 최근 평가한 앨범/트랙 정보를 포함합니다.
         * @summary 평가 기록 전체 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserRateRecords_10(userId: string, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserRateRecords200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserRateRecords_10(userId, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserRateRecords_10']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
         * @summary 평가한 앨범 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserRatedAlbums(userId: string, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserRatedAlbums200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserRatedAlbums(userId, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserRatedAlbums']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
         * @summary 평가한 앨범 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserRatedAlbums_11(userId: string, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserRatedAlbums200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserRatedAlbums_11(userId, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserRatedAlbums_11']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
         * @summary 평가한 트랙 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserRatedTracks(userId: string, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserRatedTracks200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserRatedTracks(userId, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserRatedTracks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
         * @summary 평가한 트랙 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserRatedTracks_12(userId: string, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserRatedTracks200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserRatedTracks_12(userId, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserRatedTracks_12']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary /users/{userId}
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersUserIdGet(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersUserIdGet(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.usersUserIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
         * @summary 좋아요한 아티스트 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLikedArtists(options?: RawAxiosRequestConfig): AxiosPromise<GetLikedArtists200Response> {
            return localVarFp.getLikedArtists(options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
         * @summary 좋아요한 아티스트 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLikedArtists_1(options?: RawAxiosRequestConfig): AxiosPromise<GetLikedArtists200Response> {
            return localVarFp.getLikedArtists_1(options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
         * @summary 내 활동 페이지 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyActivity(options?: RawAxiosRequestConfig): AxiosPromise<GetMyActivity200Response> {
            return localVarFp.getMyActivity(options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
         * @summary 내 활동 페이지 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyActivity_2(options?: RawAxiosRequestConfig): AxiosPromise<GetMyActivity200Response> {
            return localVarFp.getMyActivity_2(options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 인증된 사용자가 생성한 모든 컬렉션의 목록을 조회합니다. 여기에는 공개(public) 및 비공개(private) 컬렉션이 모두 포함됩니다.
         * @summary 내 컬렉션 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyCollections(options?: RawAxiosRequestConfig): AxiosPromise<GetUserCollections200Response> {
            return localVarFp.getMyCollections(options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 인증된 사용자가 생성한 모든 컬렉션의 목록을 조회합니다. 여기에는 공개(public) 및 비공개(private) 컬렉션이 모두 포함됩니다.
         * @summary 좋아요한 컬렉션 목록
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyCollections_3(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetMyCollections200Response> {
            return localVarFp.getMyCollections_3(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
         * @summary 리뷰(내용 있는) 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRatedAlbums(options?: RawAxiosRequestConfig): AxiosPromise<GetRatedAlbums200Response> {
            return localVarFp.getRatedAlbums(options).then((request) => request(axios, basePath));
        },
        /**
         * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
         * @summary 리뷰(내용 있는) 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRatedAlbums_4(options?: RawAxiosRequestConfig): AxiosPromise<GetRatedAlbums200Response> {
            return localVarFp.getRatedAlbums_4(options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 인증된 사용자가 리뷰(평가)를 남긴 모든 트랙의 목록을 조회합니다.
         * @summary 평가한 트랙 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRatedTracks(options?: RawAxiosRequestConfig): AxiosPromise<GetRatedTracks200Response> {
            return localVarFp.getRatedTracks(options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 인증된 사용자가 리뷰(평가)를 남긴 모든 트랙의 목록을 조회합니다.
         * @summary 평가한 트랙 목록
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRatedTracks_5(options?: RawAxiosRequestConfig): AxiosPromise<GetRatedTracks200Response> {
            return localVarFp.getRatedTracks_5(options).then((request) => request(axios, basePath));
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 내 칭호 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections(options?: RawAxiosRequestConfig): AxiosPromise<GetUserCollections200Response1> {
            return localVarFp.getUserCollections(options).then((request) => request(axios, basePath));
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 활성화된 칭호 확인
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections_6(options?: RawAxiosRequestConfig): AxiosPromise<GetUserCollections200Response2> {
            return localVarFp.getUserCollections_6(options).then((request) => request(axios, basePath));
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 칭호 설정
         * @param {GetUserCollectionsRequest} [getUserCollectionsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections_7(getUserCollectionsRequest?: GetUserCollectionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetUserCollections200Response3> {
            return localVarFp.getUserCollections_7(getUserCollectionsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 타인의 칭호 목록 조회
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections_8(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserCollections200Response1> {
            return localVarFp.getUserCollections_8(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자가 생성한 컬렉션 중 \'공개(public)\'로 설정된 목록만 조회합니다. 다른 사용자의 비공개 컬렉션은 이 API를 통해 조회할 수 없습니다.
         * @summary 타인의 컬렉션 목록 조회
         * @param {string} userId 조회할 사용자 ID (integer)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections_9(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserCollections200Response> {
            return localVarFp.getUserCollections_9(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자의 전체 평가 기록 페이지 정보를 조회합니다. 사용자 프로필, 통계, 별점 분포, 컬렉션, 장르 키워드, 최근 평가한 앨범/트랙 정보를 포함합니다.
         * @summary 평가 기록 전체 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRateRecords(userId: string, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserRateRecords200Response> {
            return localVarFp.getUserRateRecords(userId, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자의 전체 평가 기록 페이지 정보를 조회합니다. 사용자 프로필, 통계, 별점 분포, 컬렉션, 장르 키워드, 최근 평가한 앨범/트랙 정보를 포함합니다.
         * @summary 평가 기록 전체 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRateRecords_10(userId: string, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserRateRecords200Response> {
            return localVarFp.getUserRateRecords_10(userId, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
         * @summary 평가한 앨범 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedAlbums(userId: string, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserRatedAlbums200Response> {
            return localVarFp.getUserRatedAlbums(userId, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
         * @summary 평가한 앨범 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedAlbums_11(userId: string, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserRatedAlbums200Response> {
            return localVarFp.getUserRatedAlbums_11(userId, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
         * @summary 평가한 트랙 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedTracks(userId: string, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserRatedTracks200Response> {
            return localVarFp.getUserRatedTracks(userId, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
         * @summary 평가한 트랙 페이지
         * @param {string} userId 사용자 ID
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedTracks_12(userId: string, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserRatedTracks200Response> {
            return localVarFp.getUserRatedTracks_12(userId, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary /users/{userId}
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUserIdGet(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.usersUserIdGet(userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
     * @summary 좋아요한 아티스트 목록
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getLikedArtists(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getLikedArtists(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
     * @summary 좋아요한 아티스트 목록
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getLikedArtists_1(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getLikedArtists_1(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
     * @summary 내 활동 페이지 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getMyActivity(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getMyActivity(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
     * @summary 내 활동 페이지 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getMyActivity_2(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getMyActivity_2(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 인증된 사용자가 생성한 모든 컬렉션의 목록을 조회합니다. 여기에는 공개(public) 및 비공개(private) 컬렉션이 모두 포함됩니다.
     * @summary 내 컬렉션 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getMyCollections(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getMyCollections(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 인증된 사용자가 생성한 모든 컬렉션의 목록을 조회합니다. 여기에는 공개(public) 및 비공개(private) 컬렉션이 모두 포함됩니다.
     * @summary 좋아요한 컬렉션 목록
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getMyCollections_3(userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getMyCollections_3(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
     * @summary 리뷰(내용 있는) 목록
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getRatedAlbums(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getRatedAlbums(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
     * @summary 리뷰(내용 있는) 목록
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getRatedAlbums_4(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getRatedAlbums_4(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 인증된 사용자가 리뷰(평가)를 남긴 모든 트랙의 목록을 조회합니다.
     * @summary 평가한 트랙 목록
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getRatedTracks(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getRatedTracks(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 인증된 사용자가 리뷰(평가)를 남긴 모든 트랙의 목록을 조회합니다.
     * @summary 평가한 트랙 목록
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getRatedTracks_5(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getRatedTracks_5(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 홈 화면에 해당하는 API
     * @summary 내 칭호 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserCollections(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserCollections(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 홈 화면에 해당하는 API
     * @summary 활성화된 칭호 확인
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserCollections_6(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserCollections_6(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 홈 화면에 해당하는 API
     * @summary 칭호 설정
     * @param {GetUserCollectionsRequest} [getUserCollectionsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserCollections_7(getUserCollectionsRequest?: GetUserCollectionsRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserCollections_7(getUserCollectionsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 홈 화면에 해당하는 API
     * @summary 타인의 칭호 목록 조회
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserCollections_8(userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserCollections_8(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자가 생성한 컬렉션 중 \'공개(public)\'로 설정된 목록만 조회합니다. 다른 사용자의 비공개 컬렉션은 이 API를 통해 조회할 수 없습니다.
     * @summary 타인의 컬렉션 목록 조회
     * @param {string} userId 조회할 사용자 ID (integer)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserCollections_9(userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserCollections_9(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자의 전체 평가 기록 페이지 정보를 조회합니다. 사용자 프로필, 통계, 별점 분포, 컬렉션, 장르 키워드, 최근 평가한 앨범/트랙 정보를 포함합니다.
     * @summary 평가 기록 전체 페이지
     * @param {string} userId 사용자 ID
     * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserRateRecords(userId: string, authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserRateRecords(userId, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자의 전체 평가 기록 페이지 정보를 조회합니다. 사용자 프로필, 통계, 별점 분포, 컬렉션, 장르 키워드, 최근 평가한 앨범/트랙 정보를 포함합니다.
     * @summary 평가 기록 전체 페이지
     * @param {string} userId 사용자 ID
     * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserRateRecords_10(userId: string, authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserRateRecords_10(userId, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
     * @summary 평가한 앨범 페이지
     * @param {string} userId 사용자 ID
     * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserRatedAlbums(userId: string, authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserRatedAlbums(userId, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
     * @summary 평가한 앨범 페이지
     * @param {string} userId 사용자 ID
     * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserRatedAlbums_11(userId: string, authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserRatedAlbums_11(userId, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
     * @summary 평가한 트랙 페이지
     * @param {string} userId 사용자 ID
     * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserRatedTracks(userId: string, authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserRatedTracks(userId, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다.
     * @summary 평가한 트랙 페이지
     * @param {string} userId 사용자 ID
     * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserRatedTracks_12(userId: string, authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserRatedTracks_12(userId, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary /users/{userId}
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public usersUserIdGet(userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersUserIdGet(userId, options).then((request) => request(this.axios, this.basePath));
    }
}

