/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { GetLikedArtists200Response } from '../models';
// @ts-ignore
import type { GetMyActivity200Response } from '../models';
// @ts-ignore
import type { GetMyCollections200Response2 } from '../models';
// @ts-ignore
import type { GetMyCollections200Response3 } from '../models';
// @ts-ignore
import type { GetMyFollowing200Response } from '../models';
// @ts-ignore
import type { GetMyFollwers200Response } from '../models';
// @ts-ignore
import type { GetOthersActivity200Response } from '../models';
// @ts-ignore
import type { GetRatedAlbums200Response } from '../models';
// @ts-ignore
import type { GetUserCollections200Response1 } from '../models';
// @ts-ignore
import type { GetUserCollections200Response2 } from '../models';
// @ts-ignore
import type { GetUserCollections200Response3 } from '../models';
// @ts-ignore
import type { GetUserCollectionsRequest } from '../models';
// @ts-ignore
import type { GetUserProfile200Response } from '../models';
// @ts-ignore
import type { GetUserRatedAlbums200Response } from '../models';
// @ts-ignore
import type { GetUserRatedTracks200Response } from '../models';
/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * userId의 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
         * @summary 타인이 좋아요한 아티스트 목록
         * @param {string} userId 
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLikedArtists: async (userId: string, sortBy?: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getLikedArtists', 'userId', userId)
            const localVarPath = `/users/{userId}/liked-artist`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
         * @summary 좋아요한 아티스트 목록
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLikedArtists_1: async (sortBy?: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/liked-artist`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
         * @summary 좋아요한 아티스트 목록
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLikedArtists_2: async (sortBy?: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/liked-artist`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
         * @summary 내 활동 페이지 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyActivity: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/activity`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
         * @summary 내 활동 페이지 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyActivity_3: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/activity`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 인증된 사용자가 생성한 모든 컬렉션의 목록을 조회합니다. 여기에는 공개(public) 및 비공개(private) 컬렉션이 모두 포함됩니다.
         * @summary 내 컬렉션 목록 조회
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyCollections: async (sortBy?: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/collections`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 현재 인증된 사용자가 좋아요한 컬렉션의 목록
         * @summary 좋아요한 컬렉션 목록
         * @param {string} userId 
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyCollections_4: async (userId: string, sortBy?: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getMyCollections_4', 'userId', userId)
            const localVarPath = `/users/{userId}/collections/liked`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 인증된 사용자가 팔로우 중인 유저 목록을 조회합니다. 결과는 페이지네이션 형식으로 반환됩니다. 
         * @summary 내가 팔로우 하는 유저들의 목록 조회
         * @param {number} [page] 페이지 번호
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyFollowing: async (page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/following`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 인증된 사용자를 팔로우 중인 유저 목록을 조회합니다. 결과는 페이지네이션 형식으로 반환됩니다. 
         * @summary 나를 팔로우 하는 유저들의 목록 조회
         * @param {number} [page] 페이지 번호
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyFollwers: async (page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/followers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자의 활동 페이지를 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다. 
         * @summary 타인 활동 페이지 조회
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOthersActivity: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getOthersActivity', 'userId', userId)
            const localVarPath = `/users/{userId}/activity`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
         * @summary 리뷰(내용 있는) 목록(앨범만)
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRatedAlbums: async (sortBy?: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/review-list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
         * @summary 리뷰(내용 있는) 목록(앨범만)
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRatedAlbums_5: async (sortBy?: string, page?: number, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/review-list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 내 칭호 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/badges`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 활성화된 칭호 확인
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections_6: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/active-badge`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 칭호 설정
         * @param {GetUserCollectionsRequest} [getUserCollectionsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections_7: async (getUserCollectionsRequest?: GetUserCollectionsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/active-badge`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(getUserCollectionsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 타인의 칭호 목록 조회
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections_8: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserCollections_8', 'userId', userId)
            const localVarPath = `/users/{userId}/badges`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자의 프로필 사진과 소개글(bio)을 조회합니다. 
         * @summary 사용자 프로필 조회
         * @param {number} userId 프로필을 조회할 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserProfile: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserProfile', 'userId', userId)
            const localVarPath = `/users/{userId}/profile`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자의 프로필 사진과 소개글(bio)을 조회합니다. 
         * @summary 사용자 프로필 조회
         * @param {number} userId 프로필을 조회할 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserProfile_9: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserProfile_9', 'userId', userId)
            const localVarPath = `/users/{userId}/profile`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 평가한 내용이 없어도 모든 평가를 불러옵니다
         * @summary 평가한 앨범 페이지
         * @param {number} userId 사용자 ID
         * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedAlbums: async (userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserRatedAlbums', 'userId', userId)
            const localVarPath = `/users/{userId}/rated-albums`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 평가한 내용이 없어도 모든 평가를 불러옵니다
         * @summary 평가한 앨범 페이지
         * @param {number} userId 사용자 ID
         * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedAlbums_10: async (userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserRatedAlbums_10', 'userId', userId)
            const localVarPath = `/users/{userId}/rated-albums`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 리뷰 내용이 없어도 모든 평가를 가져옵니다
         * @summary 평가한 트랙 페이지
         * @param {number} userId 사용자 ID
         * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedTracks: async (userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserRatedTracks', 'userId', userId)
            const localVarPath = `/users/{userId}/rated-tracks`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 리뷰 내용이 없어도 모든 평가를 가져옵니다
         * @summary 평가한 트랙 페이지
         * @param {number} userId 사용자 ID
         * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedTracks_11: async (userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserRatedTracks_11', 'userId', userId)
            const localVarPath = `/users/{userId}/rated-tracks`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * userId의 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
         * @summary 타인이 좋아요한 아티스트 목록
         * @param {string} userId 
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLikedArtists(userId: string, sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetLikedArtists200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLikedArtists(userId, sortBy, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getLikedArtists']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
         * @summary 좋아요한 아티스트 목록
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLikedArtists_1(sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetLikedArtists200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLikedArtists_1(sortBy, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getLikedArtists_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
         * @summary 좋아요한 아티스트 목록
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLikedArtists_2(sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetLikedArtists200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLikedArtists_2(sortBy, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getLikedArtists_2']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
         * @summary 내 활동 페이지 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyActivity(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMyActivity200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyActivity(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getMyActivity']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
         * @summary 내 활동 페이지 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyActivity_3(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMyActivity200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyActivity_3(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getMyActivity_3']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 인증된 사용자가 생성한 모든 컬렉션의 목록을 조회합니다. 여기에는 공개(public) 및 비공개(private) 컬렉션이 모두 포함됩니다.
         * @summary 내 컬렉션 목록 조회
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyCollections(sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMyCollections200Response2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyCollections(sortBy, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getMyCollections']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 현재 인증된 사용자가 좋아요한 컬렉션의 목록
         * @summary 좋아요한 컬렉션 목록
         * @param {string} userId 
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyCollections_4(userId: string, sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMyCollections200Response3>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyCollections_4(userId, sortBy, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getMyCollections_4']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 인증된 사용자가 팔로우 중인 유저 목록을 조회합니다. 결과는 페이지네이션 형식으로 반환됩니다. 
         * @summary 내가 팔로우 하는 유저들의 목록 조회
         * @param {number} [page] 페이지 번호
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyFollowing(page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMyFollowing200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyFollowing(page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getMyFollowing']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 인증된 사용자를 팔로우 중인 유저 목록을 조회합니다. 결과는 페이지네이션 형식으로 반환됩니다. 
         * @summary 나를 팔로우 하는 유저들의 목록 조회
         * @param {number} [page] 페이지 번호
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyFollwers(page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMyFollwers200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyFollwers(page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getMyFollwers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자의 활동 페이지를 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다. 
         * @summary 타인 활동 페이지 조회
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOthersActivity(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetOthersActivity200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOthersActivity(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getOthersActivity']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
         * @summary 리뷰(내용 있는) 목록(앨범만)
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRatedAlbums(sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRatedAlbums200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRatedAlbums(sortBy, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getRatedAlbums']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
         * @summary 리뷰(내용 있는) 목록(앨범만)
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRatedAlbums_5(sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetRatedAlbums200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRatedAlbums_5(sortBy, page, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getRatedAlbums_5']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 내 칭호 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserCollections(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserCollections200Response1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserCollections(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserCollections']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 활성화된 칭호 확인
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserCollections_6(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserCollections200Response2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserCollections_6(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserCollections_6']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 칭호 설정
         * @param {GetUserCollectionsRequest} [getUserCollectionsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserCollections_7(getUserCollectionsRequest?: GetUserCollectionsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserCollections200Response3>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserCollections_7(getUserCollectionsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserCollections_7']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 타인의 칭호 목록 조회
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserCollections_8(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserCollections200Response1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserCollections_8(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserCollections_8']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자의 프로필 사진과 소개글(bio)을 조회합니다. 
         * @summary 사용자 프로필 조회
         * @param {number} userId 프로필을 조회할 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserProfile(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserProfile200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserProfile(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserProfile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자의 프로필 사진과 소개글(bio)을 조회합니다. 
         * @summary 사용자 프로필 조회
         * @param {number} userId 프로필을 조회할 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserProfile_9(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserProfile200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserProfile_9(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserProfile_9']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 평가한 내용이 없어도 모든 평가를 불러옵니다
         * @summary 평가한 앨범 페이지
         * @param {number} userId 사용자 ID
         * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserRatedAlbums(userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserRatedAlbums200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserRatedAlbums(userId, sortBy, page, limit, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserRatedAlbums']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 평가한 내용이 없어도 모든 평가를 불러옵니다
         * @summary 평가한 앨범 페이지
         * @param {number} userId 사용자 ID
         * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserRatedAlbums_10(userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserRatedAlbums200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserRatedAlbums_10(userId, sortBy, page, limit, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserRatedAlbums_10']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 리뷰 내용이 없어도 모든 평가를 가져옵니다
         * @summary 평가한 트랙 페이지
         * @param {number} userId 사용자 ID
         * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserRatedTracks(userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserRatedTracks200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserRatedTracks(userId, sortBy, page, limit, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserRatedTracks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 리뷰 내용이 없어도 모든 평가를 가져옵니다
         * @summary 평가한 트랙 페이지
         * @param {number} userId 사용자 ID
         * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserRatedTracks_11(userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetUserRatedTracks200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserRatedTracks_11(userId, sortBy, page, limit, authorization, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserRatedTracks_11']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * userId의 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
         * @summary 타인이 좋아요한 아티스트 목록
         * @param {string} userId 
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLikedArtists(userId: string, sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetLikedArtists200Response> {
            return localVarFp.getLikedArtists(userId, sortBy, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
         * @summary 좋아요한 아티스트 목록
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLikedArtists_1(sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetLikedArtists200Response> {
            return localVarFp.getLikedArtists_1(sortBy, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
         * @summary 좋아요한 아티스트 목록
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLikedArtists_2(sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetLikedArtists200Response> {
            return localVarFp.getLikedArtists_2(sortBy, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
         * @summary 내 활동 페이지 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyActivity(options?: RawAxiosRequestConfig): AxiosPromise<GetMyActivity200Response> {
            return localVarFp.getMyActivity(options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
         * @summary 내 활동 페이지 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyActivity_3(options?: RawAxiosRequestConfig): AxiosPromise<GetMyActivity200Response> {
            return localVarFp.getMyActivity_3(options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 인증된 사용자가 생성한 모든 컬렉션의 목록을 조회합니다. 여기에는 공개(public) 및 비공개(private) 컬렉션이 모두 포함됩니다.
         * @summary 내 컬렉션 목록 조회
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyCollections(sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetMyCollections200Response2> {
            return localVarFp.getMyCollections(sortBy, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 현재 인증된 사용자가 좋아요한 컬렉션의 목록
         * @summary 좋아요한 컬렉션 목록
         * @param {string} userId 
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyCollections_4(userId: string, sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetMyCollections200Response3> {
            return localVarFp.getMyCollections_4(userId, sortBy, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 인증된 사용자가 팔로우 중인 유저 목록을 조회합니다. 결과는 페이지네이션 형식으로 반환됩니다. 
         * @summary 내가 팔로우 하는 유저들의 목록 조회
         * @param {number} [page] 페이지 번호
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyFollowing(page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetMyFollowing200Response> {
            return localVarFp.getMyFollowing(page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 인증된 사용자를 팔로우 중인 유저 목록을 조회합니다. 결과는 페이지네이션 형식으로 반환됩니다. 
         * @summary 나를 팔로우 하는 유저들의 목록 조회
         * @param {number} [page] 페이지 번호
         * @param {number} [limit] 페이지당 항목 수
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyFollwers(page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetMyFollwers200Response> {
            return localVarFp.getMyFollwers(page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자의 활동 페이지를 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다. 
         * @summary 타인 활동 페이지 조회
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOthersActivity(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetOthersActivity200Response> {
            return localVarFp.getOthersActivity(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
         * @summary 리뷰(내용 있는) 목록(앨범만)
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRatedAlbums(sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetRatedAlbums200Response> {
            return localVarFp.getRatedAlbums(sortBy, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
         * @summary 리뷰(내용 있는) 목록(앨범만)
         * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRatedAlbums_5(sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<GetRatedAlbums200Response> {
            return localVarFp.getRatedAlbums_5(sortBy, page, limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 내 칭호 목록 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections(options?: RawAxiosRequestConfig): AxiosPromise<GetUserCollections200Response1> {
            return localVarFp.getUserCollections(options).then((request) => request(axios, basePath));
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 활성화된 칭호 확인
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections_6(options?: RawAxiosRequestConfig): AxiosPromise<GetUserCollections200Response2> {
            return localVarFp.getUserCollections_6(options).then((request) => request(axios, basePath));
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 칭호 설정
         * @param {GetUserCollectionsRequest} [getUserCollectionsRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections_7(getUserCollectionsRequest?: GetUserCollectionsRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetUserCollections200Response3> {
            return localVarFp.getUserCollections_7(getUserCollectionsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 홈 화면에 해당하는 API
         * @summary 타인의 칭호 목록 조회
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCollections_8(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserCollections200Response1> {
            return localVarFp.getUserCollections_8(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자의 프로필 사진과 소개글(bio)을 조회합니다. 
         * @summary 사용자 프로필 조회
         * @param {number} userId 프로필을 조회할 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserProfile(userId: number, options?: RawAxiosRequestConfig): AxiosPromise<GetUserProfile200Response> {
            return localVarFp.getUserProfile(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자의 프로필 사진과 소개글(bio)을 조회합니다. 
         * @summary 사용자 프로필 조회
         * @param {number} userId 프로필을 조회할 사용자 ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserProfile_9(userId: number, options?: RawAxiosRequestConfig): AxiosPromise<GetUserProfile200Response> {
            return localVarFp.getUserProfile_9(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 평가한 내용이 없어도 모든 평가를 불러옵니다
         * @summary 평가한 앨범 페이지
         * @param {number} userId 사용자 ID
         * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedAlbums(userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserRatedAlbums200Response> {
            return localVarFp.getUserRatedAlbums(userId, sortBy, page, limit, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 평가한 내용이 없어도 모든 평가를 불러옵니다
         * @summary 평가한 앨범 페이지
         * @param {number} userId 사용자 ID
         * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedAlbums_10(userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserRatedAlbums200Response> {
            return localVarFp.getUserRatedAlbums_10(userId, sortBy, page, limit, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 리뷰 내용이 없어도 모든 평가를 가져옵니다
         * @summary 평가한 트랙 페이지
         * @param {number} userId 사용자 ID
         * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedTracks(userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserRatedTracks200Response> {
            return localVarFp.getUserRatedTracks(userId, sortBy, page, limit, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 리뷰 내용이 없어도 모든 평가를 가져옵니다
         * @summary 평가한 트랙 페이지
         * @param {number} userId 사용자 ID
         * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
         * @param {number} [page] 페이지 번호 (1부터 시작)
         * @param {number} [limit] 페이지당 항목 수(기본 20)
         * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRatedTracks_11(userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetUserRatedTracks200Response> {
            return localVarFp.getUserRatedTracks_11(userId, sortBy, page, limit, authorization, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * userId의 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
     * @summary 타인이 좋아요한 아티스트 목록
     * @param {string} userId 
     * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [limit] 페이지당 항목 수(기본 20)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getLikedArtists(userId: string, sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getLikedArtists(userId, sortBy, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
     * @summary 좋아요한 아티스트 목록
     * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [limit] 페이지당 항목 수(기본 20)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getLikedArtists_1(sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getLikedArtists_1(sortBy, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 인증된 사용자가 \'좋아요\'를 누른 모든 아티스트의 목록을 조회합니다.
     * @summary 좋아요한 아티스트 목록
     * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [limit] 페이지당 항목 수(기본 20)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getLikedArtists_2(sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getLikedArtists_2(sortBy, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
     * @summary 내 활동 페이지 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getMyActivity(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getMyActivity(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 인증된 사용자의 활동 정보를 종합적으로 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다.
     * @summary 내 활동 페이지 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getMyActivity_3(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getMyActivity_3(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 인증된 사용자가 생성한 모든 컬렉션의 목록을 조회합니다. 여기에는 공개(public) 및 비공개(private) 컬렉션이 모두 포함됩니다.
     * @summary 내 컬렉션 목록 조회
     * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [limit] 페이지당 항목 수(기본 20)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getMyCollections(sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getMyCollections(sortBy, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 현재 인증된 사용자가 좋아요한 컬렉션의 목록
     * @summary 좋아요한 컬렉션 목록
     * @param {string} userId 
     * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [limit] 페이지당 항목 수(기본 20)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getMyCollections_4(userId: string, sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getMyCollections_4(userId, sortBy, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 인증된 사용자가 팔로우 중인 유저 목록을 조회합니다. 결과는 페이지네이션 형식으로 반환됩니다. 
     * @summary 내가 팔로우 하는 유저들의 목록 조회
     * @param {number} [page] 페이지 번호
     * @param {number} [limit] 페이지당 항목 수
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getMyFollowing(page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getMyFollowing(page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 인증된 사용자를 팔로우 중인 유저 목록을 조회합니다. 결과는 페이지네이션 형식으로 반환됩니다. 
     * @summary 나를 팔로우 하는 유저들의 목록 조회
     * @param {number} [page] 페이지 번호
     * @param {number} [limit] 페이지당 항목 수
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getMyFollwers(page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getMyFollwers(page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자의 활동 페이지를 조회합니다. 사용자의 기본 프로필 정보, 리뷰 통계, 최근에 평가한 앨범/트랙 목록, 그리고 생성하거나 좋아요한 컬렉션 목록 등을 포함합니다. 
     * @summary 타인 활동 페이지 조회
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getOthersActivity(userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getOthersActivity(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
     * @summary 리뷰(내용 있는) 목록(앨범만)
     * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [limit] 페이지당 항목 수(기본 20)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getRatedAlbums(sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getRatedAlbums(sortBy, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 별점 + 내용도 있는 앨범 리뷰 전체 목록 조회
     * @summary 리뷰(내용 있는) 목록(앨범만)
     * @param {string} [sortBy] 정렬 기준 (popularity: 인기도순, recent: 최신순, old: 오래된순)
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [limit] 페이지당 항목 수(기본 20)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getRatedAlbums_5(sortBy?: string, page?: number, limit?: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getRatedAlbums_5(sortBy, page, limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 홈 화면에 해당하는 API
     * @summary 내 칭호 목록 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserCollections(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserCollections(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 홈 화면에 해당하는 API
     * @summary 활성화된 칭호 확인
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserCollections_6(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserCollections_6(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 홈 화면에 해당하는 API
     * @summary 칭호 설정
     * @param {GetUserCollectionsRequest} [getUserCollectionsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserCollections_7(getUserCollectionsRequest?: GetUserCollectionsRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserCollections_7(getUserCollectionsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 홈 화면에 해당하는 API
     * @summary 타인의 칭호 목록 조회
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserCollections_8(userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserCollections_8(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자의 프로필 사진과 소개글(bio)을 조회합니다. 
     * @summary 사용자 프로필 조회
     * @param {number} userId 프로필을 조회할 사용자 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserProfile(userId: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserProfile(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자의 프로필 사진과 소개글(bio)을 조회합니다. 
     * @summary 사용자 프로필 조회
     * @param {number} userId 프로필을 조회할 사용자 ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserProfile_9(userId: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserProfile_9(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 평가한 내용이 없어도 모든 평가를 불러옵니다
     * @summary 평가한 앨범 페이지
     * @param {number} userId 사용자 ID
     * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [limit] 페이지당 항목 수(기본 20)
     * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserRatedAlbums(userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserRatedAlbums(userId, sortBy, page, limit, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자가 평가한 모든 앨범의 목록을 조회합니다. 앨범 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 평가한 내용이 없어도 모든 평가를 불러옵니다
     * @summary 평가한 앨범 페이지
     * @param {number} userId 사용자 ID
     * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [limit] 페이지당 항목 수(기본 20)
     * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserRatedAlbums_10(userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserRatedAlbums_10(userId, sortBy, page, limit, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 리뷰 내용이 없어도 모든 평가를 가져옵니다
     * @summary 평가한 트랙 페이지
     * @param {number} userId 사용자 ID
     * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [limit] 페이지당 항목 수(기본 20)
     * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserRatedTracks(userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserRatedTracks(userId, sortBy, page, limit, authorization, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 특정 사용자가 평가한 모든 트랙의 목록을 조회합니다. 트랙 정보, 평점, 평가 날짜, 리뷰 내용을 포함합니다. 리뷰 내용이 없어도 모든 평가를 가져옵니다
     * @summary 평가한 트랙 페이지
     * @param {number} userId 사용자 ID
     * @param {string} [sortBy] 정렬 기준 (recent: 최신순, old: 오래된순)
     * @param {number} [page] 페이지 번호 (1부터 시작)
     * @param {number} [limit] 페이지당 항목 수(기본 20)
     * @param {string} [authorization] 선택사항. 로그인 시 추가 정보 제공
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserRatedTracks_11(userId: number, sortBy?: string, page?: number, limit?: number, authorization?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserRatedTracks_11(userId, sortBy, page, limit, authorization, options).then((request) => request(this.axios, this.basePath));
    }
}

