/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ErrorResponse } from '../models';
// @ts-ignore
import type { UploadImage200Response } from '../models';
/**
 * UtilitiesApi - axios parameter creator
 * @export
 */
export const UtilitiesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 서비스 내에서 사용할 이미지(프로필 이미지, 컬렉션 커버 등)를 서버에 업로드합니다.  `multipart/form-data` 형식으로 이미지 파일을 전송해야 하며, 성공 시 업로드된 이미지에 접근할 수 있는 URL을 반환합니다 /user/me/profile-img와 비슷하게 파일을 받지만, /upload-image에서는 파일을 저장하고 접근URL을 반환할 뿐 db에 저장하지 않습니다
         * @summary 이미지 업로드
         * @param {File} file 업로드할 이미지 파일 (JPEG, PNG, GIF 지원)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadImage: async (file: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadImage', 'file', file)
            const localVarPath = `/upload-image`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 서비스 내에서 사용할 이미지(프로필 이미지, 컬렉션 커버 등)를 서버에 업로드합니다.  `multipart/form-data` 형식으로 이미지 파일을 전송해야 하며, 성공 시 업로드된 이미지에 접근할 수 있는 URL을 반환합니다 /user/me/profile-img와 비슷하게 파일을 받지만, /upload-image에서는 파일을 저장하고 접근URL을 반환할 뿐 db에 저장하지 않습니다
         * @summary 이미지 업로드
         * @param {File} file 업로드할 이미지 파일 (JPEG, PNG, GIF 지원)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadImage_1: async (file: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'file' is not null or undefined
            assertParamExists('uploadImage_1', 'file', file)
            const localVarPath = `/upload-image`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UtilitiesApi - functional programming interface
 * @export
 */
export const UtilitiesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UtilitiesApiAxiosParamCreator(configuration)
    return {
        /**
         * 서비스 내에서 사용할 이미지(프로필 이미지, 컬렉션 커버 등)를 서버에 업로드합니다.  `multipart/form-data` 형식으로 이미지 파일을 전송해야 하며, 성공 시 업로드된 이미지에 접근할 수 있는 URL을 반환합니다 /user/me/profile-img와 비슷하게 파일을 받지만, /upload-image에서는 파일을 저장하고 접근URL을 반환할 뿐 db에 저장하지 않습니다
         * @summary 이미지 업로드
         * @param {File} file 업로드할 이미지 파일 (JPEG, PNG, GIF 지원)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadImage(file: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UploadImage200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadImage(file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UtilitiesApi.uploadImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 서비스 내에서 사용할 이미지(프로필 이미지, 컬렉션 커버 등)를 서버에 업로드합니다.  `multipart/form-data` 형식으로 이미지 파일을 전송해야 하며, 성공 시 업로드된 이미지에 접근할 수 있는 URL을 반환합니다 /user/me/profile-img와 비슷하게 파일을 받지만, /upload-image에서는 파일을 저장하고 접근URL을 반환할 뿐 db에 저장하지 않습니다
         * @summary 이미지 업로드
         * @param {File} file 업로드할 이미지 파일 (JPEG, PNG, GIF 지원)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadImage_1(file: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UploadImage200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadImage_1(file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UtilitiesApi.uploadImage_1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UtilitiesApi - factory interface
 * @export
 */
export const UtilitiesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UtilitiesApiFp(configuration)
    return {
        /**
         * 서비스 내에서 사용할 이미지(프로필 이미지, 컬렉션 커버 등)를 서버에 업로드합니다.  `multipart/form-data` 형식으로 이미지 파일을 전송해야 하며, 성공 시 업로드된 이미지에 접근할 수 있는 URL을 반환합니다 /user/me/profile-img와 비슷하게 파일을 받지만, /upload-image에서는 파일을 저장하고 접근URL을 반환할 뿐 db에 저장하지 않습니다
         * @summary 이미지 업로드
         * @param {File} file 업로드할 이미지 파일 (JPEG, PNG, GIF 지원)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadImage(file: File, options?: RawAxiosRequestConfig): AxiosPromise<UploadImage200Response> {
            return localVarFp.uploadImage(file, options).then((request) => request(axios, basePath));
        },
        /**
         * 서비스 내에서 사용할 이미지(프로필 이미지, 컬렉션 커버 등)를 서버에 업로드합니다.  `multipart/form-data` 형식으로 이미지 파일을 전송해야 하며, 성공 시 업로드된 이미지에 접근할 수 있는 URL을 반환합니다 /user/me/profile-img와 비슷하게 파일을 받지만, /upload-image에서는 파일을 저장하고 접근URL을 반환할 뿐 db에 저장하지 않습니다
         * @summary 이미지 업로드
         * @param {File} file 업로드할 이미지 파일 (JPEG, PNG, GIF 지원)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadImage_1(file: File, options?: RawAxiosRequestConfig): AxiosPromise<UploadImage200Response> {
            return localVarFp.uploadImage_1(file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UtilitiesApi - object-oriented interface
 * @export
 * @class UtilitiesApi
 * @extends {BaseAPI}
 */
export class UtilitiesApi extends BaseAPI {
    /**
     * 서비스 내에서 사용할 이미지(프로필 이미지, 컬렉션 커버 등)를 서버에 업로드합니다.  `multipart/form-data` 형식으로 이미지 파일을 전송해야 하며, 성공 시 업로드된 이미지에 접근할 수 있는 URL을 반환합니다 /user/me/profile-img와 비슷하게 파일을 받지만, /upload-image에서는 파일을 저장하고 접근URL을 반환할 뿐 db에 저장하지 않습니다
     * @summary 이미지 업로드
     * @param {File} file 업로드할 이미지 파일 (JPEG, PNG, GIF 지원)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UtilitiesApi
     */
    public uploadImage(file: File, options?: RawAxiosRequestConfig) {
        return UtilitiesApiFp(this.configuration).uploadImage(file, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 서비스 내에서 사용할 이미지(프로필 이미지, 컬렉션 커버 등)를 서버에 업로드합니다.  `multipart/form-data` 형식으로 이미지 파일을 전송해야 하며, 성공 시 업로드된 이미지에 접근할 수 있는 URL을 반환합니다 /user/me/profile-img와 비슷하게 파일을 받지만, /upload-image에서는 파일을 저장하고 접근URL을 반환할 뿐 db에 저장하지 않습니다
     * @summary 이미지 업로드
     * @param {File} file 업로드할 이미지 파일 (JPEG, PNG, GIF 지원)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UtilitiesApi
     */
    public uploadImage_1(file: File, options?: RawAxiosRequestConfig) {
        return UtilitiesApiFp(this.configuration).uploadImage_1(file, options).then((request) => request(this.axios, this.basePath));
    }
}

