/**
 * API Configuration
 *
 * API 서버 설정 및 환경 변수 관리
 */

export const API_CONFIG = {
  // Base URL from environment variables
  baseURL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api',

  // Request timeout (10 seconds)
  timeout: 10000,

  // Default headers
  headers: {
    'Content-Type': 'application/json',
  },

  // Enable credentials (cookies)
  withCredentials: true,
} as const;

/**
 * Environment check
 */
export const isDevelopment = import.meta.env.VITE_ENV === 'development';
export const isProduction = import.meta.env.VITE_ENV === 'production';

/**
 * API Endpoints paths (for reference)
 * Actual API functions will be generated by APIdog
 */
export const API_PATHS = {
  // Home
  HOME: '/home',

  // Collections
  COLLECTIONS_RECOMMENDED: '/collections/recommended',
  COLLECTIONS_ALL: '/collections',
  COLLECTIONS_MY: '/collections/my',
  COLLECTIONS_LIKED: '/collections/liked',
  COLLECTIONS_CREATE: '/collections',

  // Comments
  COMMENTS_POPULAR: '/comments/popular',
  COMMENTS_RECENT: '/comments/recent',

  // Albums
  ALBUMS: '/albums',
  ALBUMS_DETAIL: '/albums/:id',
  ALBUMS_RATED: '/albums/rated',

  // Tracks
  TRACKS: '/tracks',
  TRACKS_DETAIL: '/tracks/:id',
  TRACKS_RATED: '/tracks/rated',

  // Artists
  ARTISTS: '/artists',
  ARTISTS_DETAIL: '/artists/:id',
  ARTISTS_LIKED: '/artists/liked',

  // Reviews
  REVIEWS: '/reviews',
  REVIEWS_MY: '/reviews/my',

  // Search
  SEARCH: '/search',

  // Auth
  AUTH_LOGIN: '/auth/login',
  AUTH_REGISTER: '/auth/register',
  AUTH_LOGOUT: '/auth/logout',

  // User
  USER_PROFILE: '/user/profile',
  USER_DETAIL: '/user/:id',
} as const;
