/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ArtistDetailAlbumsInner
 */
export interface ArtistDetailAlbumsInner {
    /**
     * 앨범 ID
     * @type {string}
     * @memberof ArtistDetailAlbumsInner
     */
    'id': string;
    /**
     * 앨범 제목
     * @type {string}
     * @memberof ArtistDetailAlbumsInner
     */
    'title': string;
    /**
     * 앨범 커버 이미지 URL
     * @type {string}
     * @memberof ArtistDetailAlbumsInner
     */
    'imageUrl': string;
    /**
     * 발매일
     * @type {string}
     * @memberof ArtistDetailAlbumsInner
     */
    'releaseDate': string;
}

