/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ArtistPreview
 */
export interface ArtistPreview {
    /**
     * 아티스트 ID
     * @type {string}
     * @memberof ArtistPreview
     */
    'artistId': string;
    /**
     * 아티스트 이름
     * @type {string}
     * @memberof ArtistPreview
     */
    'name': string;
    /**
     * 아티스트 이미지 URL
     * @type {string}
     * @memberof ArtistPreview
     */
    'imageUrl': string;
}

