/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CollectionItem
 */
export interface CollectionItem {
    /**
     * 아이템 ID
     * @type {number}
     * @memberof CollectionItem
     */
    'id': number;
    /**
     * 아이템 타입
     * @type {string}
     * @memberof CollectionItem
     */
    'type': CollectionItemTypeEnum;
    /**
     * 제목
     * @type {string}
     * @memberof CollectionItem
     */
    'title': string;
    /**
     * 아티스트 목록
     * @type {Array<string>}
     * @memberof CollectionItem
     */
    'artists'?: Array<string>;
    /**
     * 커버 이미지 URL
     * @type {string}
     * @memberof CollectionItem
     */
    'coverUrl': string;
    /**
     * 평균 평점
     * @type {number}
     * @memberof CollectionItem
     */
    'rating': number;
    /**
     * 컬렉션 생성자가 작성한 아이템 설명
     * @type {string}
     * @memberof CollectionItem
     */
    'description'?: string;
}

export const CollectionItemTypeEnum = {
    Album: 'album',
    Track: 'track'
} as const;

export type CollectionItemTypeEnum = typeof CollectionItemTypeEnum[keyof typeof CollectionItemTypeEnum];


