/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CollectionItemInput
 */
export interface CollectionItemInput {
    /**
     * 아이템 타입
     * @type {number}
     * @memberof CollectionItemInput
     */
    'type': number;
    /**
     * 아이템 ID (Spotify ID)
     * @type {string}
     * @memberof CollectionItemInput
     */
    'id': string;
    /**
     * 아이템에 대한 제목
     * @type {string}
     * @memberof CollectionItemInput
     */
    'title': string;
    /**
     * 아이템에 대한 설명 (선택사항)
     * @type {string}
     * @memberof CollectionItemInput
     */
    'description'?: string;
    /**
     * 아이템에 대한 커버 이미지 경로
     * @type {string}
     * @memberof CollectionItemInput
     */
    'coverUrl': string;
    /**
     * 부른 가수 리스트
     * @type {Array<string>}
     * @memberof CollectionItemInput
     */
    'artists': Array<string>;
}

