/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * 댓글 고유 ID
     * @type {number}
     * @memberof Comment
     */
    'commentId': number;
    /**
     * 댓글 내용
     * @type {string}
     * @memberof Comment
     */
    'content': string;
    /**
     * 작성자 닉네임
     * @type {string}
     * @memberof Comment
     */
    'userName': string;
    /**
     * 작성자 프로필 이미지 URL
     * @type {string}
     * @memberof Comment
     */
    'profileImageUrl': string;
    /**
     * 작성일시 (ISO 8601 형식)
     * @type {string}
     * @memberof Comment
     */
    'createdAt': string;
    /**
     * 수정일시 (수정된 경우에만)
     * @type {string}
     * @memberof Comment
     */
    'updatedAt'?: string;
    /**
     * 대댓글인 경우 부모 댓글 ID, 없으면 null
     * @type {number}
     * @memberof Comment
     */
    'parentId'?: number;
    /**
     * 좋아요 개수
     * @type {number}
     * @memberof Comment
     */
    'likeCount': number;
    /**
     * 대댓글 개수 (부모 댓글인 경우에만)
     * @type {number}
     * @memberof Comment
     */
    'commentCount'?: number;
    /**
     * 현재 사용자의 좋아요 여부 (로그인 시에만)
     * @type {boolean}
     * @memberof Comment
     */
    'isLiked': boolean;
}

