/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateComment200ResponseAllOfData
 */
export interface CreateComment200ResponseAllOfData {
    /**
     * 생성된 댓글 ID
     * @type {string}
     * @memberof CreateComment200ResponseAllOfData
     */
    'commentId'?: string;
    /**
     * 댓글이 작성된 대상 타입
     * @type {string}
     * @memberof CreateComment200ResponseAllOfData
     */
    'type'?: string;
    /**
     * 댓글이 작성된 대상 ID
     * @type {string}
     * @memberof CreateComment200ResponseAllOfData
     */
    'targetId'?: string;
    /**
     * 작성자 닉네임
     * @type {string}
     * @memberof CreateComment200ResponseAllOfData
     */
    'username'?: string;
    /**
     * 댓글 내용
     * @type {string}
     * @memberof CreateComment200ResponseAllOfData
     */
    'content'?: string;
    /**
     * 작성일시
     * @type {string}
     * @memberof CreateComment200ResponseAllOfData
     */
    'createdAt'?: string;
}

