/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateReview200ResponseAllOfData
 */
export interface CreateReview200ResponseAllOfData {
    /**
     * 생성된 리뷰의 ID
     * @type {string}
     * @memberof CreateReview200ResponseAllOfData
     */
    'reviewId'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReview200ResponseAllOfData
     */
    'message'?: string;
}

