/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CollectionItem } from './collection-item';
// May contain unused imports in some cases
// @ts-ignore
import type { Comment } from './comment';
// May contain unused imports in some cases
// @ts-ignore
import type { UserPreview } from './user-preview';

/**
 * 
 * @export
 * @interface CreateCollection200ResponseAllOfData
 */
export interface CreateCollection200ResponseAllOfData {
    /**
     * 컬렉션 ID
     * @type {number}
     * @memberof CreateCollection200ResponseAllOfData
     */
    'collectionId': number;
    /**
     * 컬렉션 제목
     * @type {string}
     * @memberof CreateCollection200ResponseAllOfData
     */
    'title': string;
    /**
     * 
     * @type {UserPreview}
     * @memberof CreateCollection200ResponseAllOfData
     */
    'author': UserPreview;
    /**
     * 컬렉션 설명
     * @type {string}
     * @memberof CreateCollection200ResponseAllOfData
     */
    'description': string;
    /**
     * 생성일시
     * @type {string}
     * @memberof CreateCollection200ResponseAllOfData
     */
    'createdAt': string;
    /**
     * 수정일시
     * @type {string}
     * @memberof CreateCollection200ResponseAllOfData
     */
    'updatedAt'?: string;
    /**
     * 커버 이미지 URL
     * @type {string}
     * @memberof CreateCollection200ResponseAllOfData
     */
    'coverImgUrl': string;
    /**
     * 태그 목록
     * @type {Array<string>}
     * @memberof CreateCollection200ResponseAllOfData
     */
    'tags': Array<string>;
    /**
     * 댓글 개수
     * @type {number}
     * @memberof CreateCollection200ResponseAllOfData
     */
    'commentCount': number;
    /**
     * 좋아요 개수
     * @type {number}
     * @memberof CreateCollection200ResponseAllOfData
     */
    'likeCount': number;
    /**
     * 현재 사용자의 좋아요 여부 (로그인 시에만)
     * @type {boolean}
     * @memberof CreateCollection200ResponseAllOfData
     */
    'isLiked'?: boolean;
    /**
     * 컬렉션에 포함된 모든 아이템
     * @type {Array<CollectionItem>}
     * @memberof CreateCollection200ResponseAllOfData
     */
    'items': Array<CollectionItem>;
    /**
     * 최근 댓글 (최대 3개)
     * @type {Array<Comment>}
     * @memberof CreateCollection200ResponseAllOfData
     */
    'comments': Array<Comment>;
    /**
     * 공개 여부
     * @type {string}
     * @memberof CreateCollection200ResponseAllOfData
     */
    'isPublic'?: CreateCollection200ResponseAllOfDataIsPublicEnum;
}

export const CreateCollection200ResponseAllOfDataIsPublicEnum = {
    Public: 'public',
    Private: 'private'
} as const;

export type CreateCollection200ResponseAllOfDataIsPublicEnum = typeof CreateCollection200ResponseAllOfDataIsPublicEnum[keyof typeof CreateCollection200ResponseAllOfDataIsPublicEnum];


