/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CollectionPreview } from './collection-preview';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginationInfo } from './pagination-info';

/**
 * 
 * @export
 * @interface GetMyCollections200Response1AllOfData
 */
export interface GetMyCollections200Response1AllOfData {
    /**
     * 
     * @type {Array<CollectionPreview>}
     * @memberof GetMyCollections200Response1AllOfData
     */
    'collections'?: Array<CollectionPreview>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof GetMyCollections200Response1AllOfData
     */
    'pagination': PaginationInfo;
}

