/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AlbumPreview } from './album-preview';

/**
 * 
 * @export
 * @interface GetAlbumDetail200ResponseAllOfDataReviewsInner
 */
export interface GetAlbumDetail200ResponseAllOfDataReviewsInner {
    /**
     * 리뷰 ID
     * @type {number}
     * @memberof GetAlbumDetail200ResponseAllOfDataReviewsInner
     */
    'reviewId': number;
    /**
     * 작성자 ID
     * @type {number}
     * @memberof GetAlbumDetail200ResponseAllOfDataReviewsInner
     */
    'userId': number;
    /**
     * 작성자 닉네임
     * @type {string}
     * @memberof GetAlbumDetail200ResponseAllOfDataReviewsInner
     */
    'username': string;
    /**
     * 작성자 프로필 이미지 URL
     * @type {string}
     * @memberof GetAlbumDetail200ResponseAllOfDataReviewsInner
     */
    'userProfileImage': string;
    /**
     * 별점 (0.5 ~ 5.0)
     * @type {number}
     * @memberof GetAlbumDetail200ResponseAllOfDataReviewsInner
     */
    'rating': number;
    /**
     * 리뷰 내용 미리보기
     * @type {string}
     * @memberof GetAlbumDetail200ResponseAllOfDataReviewsInner
     */
    'content': string;
    /**
     * 좋아요 개수
     * @type {number}
     * @memberof GetAlbumDetail200ResponseAllOfDataReviewsInner
     */
    'likeCount': number;
    /**
     * 댓글 개수
     * @type {number}
     * @memberof GetAlbumDetail200ResponseAllOfDataReviewsInner
     */
    'commentCount': number;
    /**
     * 작성일시
     * @type {string}
     * @memberof GetAlbumDetail200ResponseAllOfDataReviewsInner
     */
    'createdAt': string;
    /**
     * 
     * @type {AlbumPreview}
     * @memberof GetAlbumDetail200ResponseAllOfDataReviewsInner
     */
    'album': AlbumPreview;
}

