/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetUserProfile200ResponseAllOfData } from './get-user-profile200-response-all-of-data';

/**
 * 
 * @export
 * @interface GetUserProfile200Response
 */
export interface GetUserProfile200Response {
    /**
     * 
     * @type {GetUserProfile200ResponseAllOfData}
     * @memberof GetUserProfile200Response
     */
    'data'?: GetUserProfile200ResponseAllOfData;
}

