/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetUserRateRecords200ResponseAllOfDataGenreKeywordsInner
 */
export interface GetUserRateRecords200ResponseAllOfDataGenreKeywordsInner {
    /**
     * 장르 이름
     * @type {string}
     * @memberof GetUserRateRecords200ResponseAllOfDataGenreKeywordsInner
     */
    'name': string;
    /**
     * 가중치 (평가한 곡 수에 비례)
     * @type {number}
     * @memberof GetUserRateRecords200ResponseAllOfDataGenreKeywordsInner
     */
    'weight': number;
    /**
     * 표시 색상 (옵션)
     * @type {string}
     * @memberof GetUserRateRecords200ResponseAllOfDataGenreKeywordsInner
     */
    'color'?: string;
}

