/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetUserRateRecords200ResponseAllOfDataLikedCollectionsInner
 */
export interface GetUserRateRecords200ResponseAllOfDataLikedCollectionsInner {
    /**
     * 컬렉션 ID
     * @type {number}
     * @memberof GetUserRateRecords200ResponseAllOfDataLikedCollectionsInner
     */
    'collectionId': number;
    /**
     * 컬렉션 제목
     * @type {string}
     * @memberof GetUserRateRecords200ResponseAllOfDataLikedCollectionsInner
     */
    'title': string;
    /**
     * 설명
     * @type {string}
     * @memberof GetUserRateRecords200ResponseAllOfDataLikedCollectionsInner
     */
    'description'?: string;
    /**
     * 제작자 이름
     * @type {string}
     * @memberof GetUserRateRecords200ResponseAllOfDataLikedCollectionsInner
     */
    'creatorName': string;
    /**
     * 수록 곡 수
     * @type {number}
     * @memberof GetUserRateRecords200ResponseAllOfDataLikedCollectionsInner
     */
    'itemCount': number;
    /**
     * 좋아요 수
     * @type {number}
     * @memberof GetUserRateRecords200ResponseAllOfDataLikedCollectionsInner
     */
    'likesCount': number;
}

