/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TrackPreview } from './track-preview';

/**
 * 
 * @export
 * @interface GetUserCollections200Response6AllOfData
 */
export interface GetUserCollections200Response6AllOfData {
    /**
     * 인기순으로 100개
     * @type {Array<TrackPreview>}
     * @memberof GetUserCollections200Response6AllOfData
     */
    'popularTracks': Array<TrackPreview>;
}

