/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetUserRateRecords200ResponseAllOfDataStatistics
 */
export interface GetUserRateRecords200ResponseAllOfDataStatistics {
    /**
     * 앨범 리뷰 수
     * @type {number}
     * @memberof GetUserRateRecords200ResponseAllOfDataStatistics
     */
    'albumReviewCount': number;
    /**
     * 트랙 리뷰 수
     * @type {number}
     * @memberof GetUserRateRecords200ResponseAllOfDataStatistics
     */
    'trackReviewCount': number;
    /**
     * 받은 좋아요 수
     * @type {number}
     * @memberof GetUserRateRecords200ResponseAllOfDataStatistics
     */
    'likeCount': number;
    /**
     * 좋아요한 아티스트 수
     * @type {number}
     * @memberof GetUserRateRecords200ResponseAllOfDataStatistics
     */
    'likedArtistCount': number;
}

