/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ArtistPreview } from './artist-preview';
// May contain unused imports in some cases
// @ts-ignore
import type { CollectionPreview } from './collection-preview';
// May contain unused imports in some cases
// @ts-ignore
import type { GetAlbumDetail200ResponseAllOfDataReviewsInner } from './get-album-detail200-response-all-of-data-reviews-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { RatingDistribution } from './rating-distribution';
// May contain unused imports in some cases
// @ts-ignore
import type { TrackPreview } from './track-preview';

/**
 * 
 * @export
 * @interface GetAlbumDetail200ResponseAllOfData
 */
export interface GetAlbumDetail200ResponseAllOfData {
    /**
     * 앨범 ID
     * @type {string}
     * @memberof GetAlbumDetail200ResponseAllOfData
     */
    'id': string;
    /**
     * 앨범 제목
     * @type {string}
     * @memberof GetAlbumDetail200ResponseAllOfData
     */
    'title': string;
    /**
     * 앨범 커버 이미지 URL
     * @type {string}
     * @memberof GetAlbumDetail200ResponseAllOfData
     */
    'imageUrl': string;
    /**
     * 아티스트 목록
     * @type {Array<ArtistPreview>}
     * @memberof GetAlbumDetail200ResponseAllOfData
     */
    'artists': Array<ArtistPreview>;
    /**
     * 평균 평점
     * @type {number}
     * @memberof GetAlbumDetail200ResponseAllOfData
     */
    'averageRating': number;
    /**
     * 평가 개수
     * @type {number}
     * @memberof GetAlbumDetail200ResponseAllOfData
     */
    'ratingCount': number;
    /**
     * 
     * @type {RatingDistribution}
     * @memberof GetAlbumDetail200ResponseAllOfData
     */
    'ratingDistribution': RatingDistribution;
    /**
     * 수록곡 목록
     * @type {Array<TrackPreview>}
     * @memberof GetAlbumDetail200ResponseAllOfData
     */
    'tracks': Array<TrackPreview>;
    /**
     * 발매일 (YYYY-MM-DD)
     * @type {string}
     * @memberof GetAlbumDetail200ResponseAllOfData
     */
    'releaseDate': string;
    /**
     * 이 앨범이 포함된 컬렉션 목록
     * @type {Array<CollectionPreview>}
     * @memberof GetAlbumDetail200ResponseAllOfData
     */
    'collections': Array<CollectionPreview>;
    /**
     * 현재 사용자가 준 평점 (로그인 시에만)
     * @type {number}
     * @memberof GetAlbumDetail200ResponseAllOfData
     */
    'userRating'?: number;
    /**
     * 현재 사용자가 평가했는지 여부 (로그인 시에만)
     * @type {boolean}
     * @memberof GetAlbumDetail200ResponseAllOfData
     */
    'isRated'?: boolean;
    /**
     * 내용 있는 리뷰(rate와 다름)
     * @type {Array<GetAlbumDetail200ResponseAllOfDataReviewsInner>}
     * @memberof GetAlbumDetail200ResponseAllOfData
     */
    'reviews': Array<GetAlbumDetail200ResponseAllOfDataReviewsInner>;
    /**
     * 내용 있는 리뷰의 개수
     * @type {number}
     * @memberof GetAlbumDetail200ResponseAllOfData
     */
    'reviewCount': number;
}

