/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetOtherRatedAlbums200ResponseAllOfDataReviewsInner } from './get-other-rated-albums200-response-all-of-data-reviews-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginationInfo } from './pagination-info';

/**
 * 
 * @export
 * @interface GetOtherRatedAlbums200ResponseAllOfData
 */
export interface GetOtherRatedAlbums200ResponseAllOfData {
    /**
     * 
     * @type {Array<GetOtherRatedAlbums200ResponseAllOfDataReviewsInner>}
     * @memberof GetOtherRatedAlbums200ResponseAllOfData
     */
    'reviews'?: Array<GetOtherRatedAlbums200ResponseAllOfDataReviewsInner>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof GetOtherRatedAlbums200ResponseAllOfData
     */
    'pagination': PaginationInfo;
}

