/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CollectionDetail } from './collection-detail';
// May contain unused imports in some cases
// @ts-ignore
import type { SuccessResponse } from './success-response';

/**
 * @type GetCollectionDetail200Response
 * @export
 */
export type GetCollectionDetail200Response = SuccessResponse;


