/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetMyCollections200Response3AllOfDataCollectionsInner } from './get-my-collections200-response3-all-of-data-collections-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginationInfo } from './pagination-info';

/**
 * 
 * @export
 * @interface GetMyCollections200Response3AllOfData
 */
export interface GetMyCollections200Response3AllOfData {
    /**
     * 
     * @type {Array<GetMyCollections200Response3AllOfDataCollectionsInner>}
     * @memberof GetMyCollections200Response3AllOfData
     */
    'collections'?: Array<GetMyCollections200Response3AllOfDataCollectionsInner>;
    /**
     * 
     * @type {PaginationInfo}
     * @memberof GetMyCollections200Response3AllOfData
     */
    'pagination': PaginationInfo;
}

