/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetOtherRatedAlbums200ResponseAllOfDataReviewsInnerAlbum } from './get-other-rated-albums200-response-all-of-data-reviews-inner-album';

/**
 * 
 * @export
 * @interface GetOtherRatedAlbums200ResponseAllOfDataReviewsInner
 */
export interface GetOtherRatedAlbums200ResponseAllOfDataReviewsInner {
    /**
     * 리뷰 ID
     * @type {number}
     * @memberof GetOtherRatedAlbums200ResponseAllOfDataReviewsInner
     */
    'reviewId': number;
    /**
     * 별점 (0.5 ~ 5.0)
     * @type {number}
     * @memberof GetOtherRatedAlbums200ResponseAllOfDataReviewsInner
     */
    'rating': number;
    /**
     * 리뷰 제목
     * @type {string}
     * @memberof GetOtherRatedAlbums200ResponseAllOfDataReviewsInner
     */
    'title'?: string | null;
    /**
     * 리뷰 내용 미리보기
     * @type {string}
     * @memberof GetOtherRatedAlbums200ResponseAllOfDataReviewsInner
     */
    'content': string;
    /**
     * 좋아요 개수
     * @type {number}
     * @memberof GetOtherRatedAlbums200ResponseAllOfDataReviewsInner
     */
    'likeCount': number;
    /**
     * 
     * @type {boolean}
     * @memberof GetOtherRatedAlbums200ResponseAllOfDataReviewsInner
     */
    'isLiked': boolean;
    /**
     * 댓글 개수
     * @type {number}
     * @memberof GetOtherRatedAlbums200ResponseAllOfDataReviewsInner
     */
    'commentCount': number;
    /**
     * 작성일시
     * @type {string}
     * @memberof GetOtherRatedAlbums200ResponseAllOfDataReviewsInner
     */
    'createdAt': string;
    /**
     * 
     * @type {GetOtherRatedAlbums200ResponseAllOfDataReviewsInnerAlbum}
     * @memberof GetOtherRatedAlbums200ResponseAllOfDataReviewsInner
     */
    'album': GetOtherRatedAlbums200ResponseAllOfDataReviewsInnerAlbum;
}

