/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserPreview } from './user-preview';

/**
 * 
 * @export
 * @interface GetMyCollections200Response3AllOfDataCollectionsInner
 */
export interface GetMyCollections200Response3AllOfDataCollectionsInner {
    /**
     * 컬렉션 ID
     * @type {number}
     * @memberof GetMyCollections200Response3AllOfDataCollectionsInner
     */
    'collectionId': number;
    /**
     * 컬렉션 제목
     * @type {string}
     * @memberof GetMyCollections200Response3AllOfDataCollectionsInner
     */
    'title': string;
    /**
     * 컬렉션 설명
     * @type {string}
     * @memberof GetMyCollections200Response3AllOfDataCollectionsInner
     */
    'description': string;
    /**
     * 
     * @type {UserPreview}
     * @memberof GetMyCollections200Response3AllOfDataCollectionsInner
     */
    'author': UserPreview;
    /**
     * 컬렉션에 포함된 아이템 개수
     * @type {number}
     * @memberof GetMyCollections200Response3AllOfDataCollectionsInner
     */
    'itemCount': number;
    /**
     * 받은 좋아요 수
     * @type {number}
     * @memberof GetMyCollections200Response3AllOfDataCollectionsInner
     */
    'likeCount': number;
    /**
     * 커버 이미지 URL
     * @type {string}
     * @memberof GetMyCollections200Response3AllOfDataCollectionsInner
     */
    'coverImageUrl': string;
    /**
     * 공개 여부
     * @type {string}
     * @memberof GetMyCollections200Response3AllOfDataCollectionsInner
     */
    'visibility'?: GetMyCollections200Response3AllOfDataCollectionsInnerVisibilityEnum;
    /**
     * 좋아요한 날짜
     * @type {string}
     * @memberof GetMyCollections200Response3AllOfDataCollectionsInner
     */
    'likedDate': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetMyCollections200Response3AllOfDataCollectionsInner
     */
    'tags': Array<string>;
}

export const GetMyCollections200Response3AllOfDataCollectionsInnerVisibilityEnum = {
    Public: 'public',
    Private: 'private'
} as const;

export type GetMyCollections200Response3AllOfDataCollectionsInnerVisibilityEnum = typeof GetMyCollections200Response3AllOfDataCollectionsInnerVisibilityEnum[keyof typeof GetMyCollections200Response3AllOfDataCollectionsInnerVisibilityEnum];


