/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetUserCollections200Response2Data
 */
export interface GetUserCollections200Response2Data {
    /**
     * 칭호 넘버
     * @type {number}
     * @memberof GetUserCollections200Response2Data
     */
    'badgeId': number;
    /**
     * 칭호
     * @type {string}
     * @memberof GetUserCollections200Response2Data
     */
    'badgeName': string;
    /**
     * 칭호 얻는 조건
     * @type {string}
     * @memberof GetUserCollections200Response2Data
     */
    'description': string;
}

