/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetRatedAlbums200ResponseAllOfDataReviewsInnerAlbum
 */
export interface GetRatedAlbums200ResponseAllOfDataReviewsInnerAlbum {
    /**
     * 
     * @type {string}
     * @memberof GetRatedAlbums200ResponseAllOfDataReviewsInnerAlbum
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof GetRatedAlbums200ResponseAllOfDataReviewsInnerAlbum
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof GetRatedAlbums200ResponseAllOfDataReviewsInnerAlbum
     */
    'artist': string;
    /**
     * 앨범 커버
     * @type {string}
     * @memberof GetRatedAlbums200ResponseAllOfDataReviewsInnerAlbum
     */
    'imageUrl': string;
}

