/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetUserRatedAlbums200ResponseAllOfDataAlbumsInner
 */
export interface GetUserRatedAlbums200ResponseAllOfDataAlbumsInner {
    /**
     * 앨범 ID
     * @type {string}
     * @memberof GetUserRatedAlbums200ResponseAllOfDataAlbumsInner
     */
    'id': string;
    /**
     * 앨범 커버 이미지
     * @type {string}
     * @memberof GetUserRatedAlbums200ResponseAllOfDataAlbumsInner
     */
    'imageUrl': string;
    /**
     * 앨범 제목
     * @type {string}
     * @memberof GetUserRatedAlbums200ResponseAllOfDataAlbumsInner
     */
    'title': string;
    /**
     * 아티스트 목록
     * @type {Array<string>}
     * @memberof GetUserRatedAlbums200ResponseAllOfDataAlbumsInner
     */
    'artists': Array<string>;
    /**
     * 리뷰 ID
     * @type {number}
     * @memberof GetUserRatedAlbums200ResponseAllOfDataAlbumsInner
     */
    'reviewId': number;
    /**
     * 내가 준 평점 (0.5~5)
     * @type {number}
     * @memberof GetUserRatedAlbums200ResponseAllOfDataAlbumsInner
     */
    'rating': number;
    /**
     * 평가 날짜 (ISO 8601 format)
     * @type {string}
     * @memberof GetUserRatedAlbums200ResponseAllOfDataAlbumsInner
     */
    'ratedDate': string;
    /**
     * 리뷰 내용 (없으면 빈 스트링)
     * @type {string}
     * @memberof GetUserRatedAlbums200ResponseAllOfDataAlbumsInner
     */
    'content': string;
}

