/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetMyCollections200Response3AllOfData } from './get-my-collections200-response3-all-of-data';
// May contain unused imports in some cases
// @ts-ignore
import type { SuccessResponse } from './success-response';

/**
 * @type GetMyCollections200Response3
 * @export
 */
export type GetMyCollections200Response3 = SuccessResponse;


