/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetUserRatedAlbums200ResponseAllOfDataAlbumsInner } from './get-user-rated-albums200-response-all-of-data-albums-inner';

/**
 * 
 * @export
 * @interface GetUserRatedAlbums200ResponseAllOfData
 */
export interface GetUserRatedAlbums200ResponseAllOfData {
    /**
     * 전체 평가한 앨범 수
     * @type {number}
     * @memberof GetUserRatedAlbums200ResponseAllOfData
     */
    'totalCount': number;
    /**
     * 
     * @type {Array<GetUserRatedAlbums200ResponseAllOfDataAlbumsInner>}
     * @memberof GetUserRatedAlbums200ResponseAllOfData
     */
    'albums': Array<GetUserRatedAlbums200ResponseAllOfDataAlbumsInner>;
}

