/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetUserRateRecords200ResponseAllOfDataGenreKeywordsInner } from './get-user-rate-records200-response-all-of-data-genre-keywords-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GetUserRateRecords200ResponseAllOfDataLikedCollectionsInner } from './get-user-rate-records200-response-all-of-data-liked-collections-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GetUserRateRecords200ResponseAllOfDataMyCollectionsInner } from './get-user-rate-records200-response-all-of-data-my-collections-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GetUserRateRecords200ResponseAllOfDataStatistics } from './get-user-rate-records200-response-all-of-data-statistics';
// May contain unused imports in some cases
// @ts-ignore
import type { GetUserRateRecords200ResponseAllOfDataUserProfile } from './get-user-rate-records200-response-all-of-data-user-profile';
// May contain unused imports in some cases
// @ts-ignore
import type { RatedAlbum } from './rated-album';
// May contain unused imports in some cases
// @ts-ignore
import type { RatedTrack } from './rated-track';
// May contain unused imports in some cases
// @ts-ignore
import type { RatingDistribution } from './rating-distribution';

/**
 * 
 * @export
 * @interface GetUserRateRecords200ResponseAllOfData
 */
export interface GetUserRateRecords200ResponseAllOfData {
    /**
     * 
     * @type {GetUserRateRecords200ResponseAllOfDataUserProfile}
     * @memberof GetUserRateRecords200ResponseAllOfData
     */
    'userProfile': GetUserRateRecords200ResponseAllOfDataUserProfile;
    /**
     * 
     * @type {GetUserRateRecords200ResponseAllOfDataStatistics}
     * @memberof GetUserRateRecords200ResponseAllOfData
     */
    'statistics': GetUserRateRecords200ResponseAllOfDataStatistics;
    /**
     * 
     * @type {RatingDistribution}
     * @memberof GetUserRateRecords200ResponseAllOfData
     */
    'albumRateDistribution': RatingDistribution;
    /**
     * 
     * @type {RatingDistribution}
     * @memberof GetUserRateRecords200ResponseAllOfData
     */
    'trackRateDistribution': RatingDistribution;
    /**
     * 내가 만든 컬렉션
     * @type {Array<GetUserRateRecords200ResponseAllOfDataMyCollectionsInner>}
     * @memberof GetUserRateRecords200ResponseAllOfData
     */
    'myCollections': Array<GetUserRateRecords200ResponseAllOfDataMyCollectionsInner>;
    /**
     * 좋아요한 컬렉션
     * @type {Array<GetUserRateRecords200ResponseAllOfDataLikedCollectionsInner>}
     * @memberof GetUserRateRecords200ResponseAllOfData
     */
    'likedCollections': Array<GetUserRateRecords200ResponseAllOfDataLikedCollectionsInner>;
    /**
     * 장르 키워드
     * @type {Array<GetUserRateRecords200ResponseAllOfDataGenreKeywordsInner>}
     * @memberof GetUserRateRecords200ResponseAllOfData
     */
    'genreKeywords': Array<GetUserRateRecords200ResponseAllOfDataGenreKeywordsInner>;
    /**
     * 최근 평가한 앨범
     * @type {Array<RatedAlbum>}
     * @memberof GetUserRateRecords200ResponseAllOfData
     */
    'ratedAlbums': Array<RatedAlbum>;
    /**
     * 최근 평가한 트랙
     * @type {Array<RatedTrack>}
     * @memberof GetUserRateRecords200ResponseAllOfData
     */
    'ratedTracks': Array<RatedTrack>;
}

