/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AlbumPreview } from './album-preview';
// May contain unused imports in some cases
// @ts-ignore
import type { ReviewSummary } from './review-summary';
// May contain unused imports in some cases
// @ts-ignore
import type { TrackPreview } from './track-preview';

/**
 * 
 * @export
 * @interface GetUserCollections200Response4AllOfData
 */
export interface GetUserCollections200Response4AllOfData {
    /**
     * 사용자 취향 맞춤 컬렉션
     * @type {Array<string>}
     * @memberof GetUserCollections200Response4AllOfData
     */
    'recommandedCollections': Array<string>;
    /**
     * 인기 많은 리뷰(단위시간)
     * @type {Array<ReviewSummary>}
     * @memberof GetUserCollections200Response4AllOfData
     */
    'popularReviews': Array<ReviewSummary>;
    /**
     * 최신 리뷰
     * @type {Array<ReviewSummary>}
     * @memberof GetUserCollections200Response4AllOfData
     */
    'recentReviews': Array<ReviewSummary>;
    /**
     * 인기순으로 10개
     * @type {Array<AlbumPreview>}
     * @memberof GetUserCollections200Response4AllOfData
     */
    'popularAlbums': Array<AlbumPreview>;
    /**
     * 인기순으로 10개
     * @type {Array<TrackPreview>}
     * @memberof GetUserCollections200Response4AllOfData
     */
    'popularTracks': Array<TrackPreview>;
}

