/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetUserCollections200Response1DataInner } from './get-user-collections200-response1-data-inner';

/**
 * 
 * @export
 * @interface GetUserCollections200Response1
 */
export interface GetUserCollections200Response1 {
    /**
     * 
     * @type {boolean}
     * @memberof GetUserCollections200Response1
     */
    'success': boolean;
    /**
     * 
     * @type {Array<GetUserCollections200Response1DataInner>}
     * @memberof GetUserCollections200Response1
     */
    'data': Array<GetUserCollections200Response1DataInner>;
    /**
     * 조회한 시각
     * @type {string}
     * @memberof GetUserCollections200Response1
     */
    'timestamp': string;
}

