/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Notification } from './notification';

/**
 * 
 * @export
 * @interface GetNotifications200ResponseAllOfData
 */
export interface GetNotifications200ResponseAllOfData {
    /**
     * 
     * @type {Array<Notification>}
     * @memberof GetNotifications200ResponseAllOfData
     */
    'notifications': Array<Notification>;
    /**
     * 읽지 않은 알림 수
     * @type {number}
     * @memberof GetNotifications200ResponseAllOfData
     */
    'unreadCount': number;
}

