/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NotificationActor
 */
export interface NotificationActor {
    /**
     * @type {number}
     * @memberof NotificationActor
     */
    'id': number;
    /**
     * @type {string}
     * @memberof NotificationActor
     */
    'username': string;
    /**
     * @type {string}
     * @memberof NotificationActor
     */
    'profileImage': string;
}

/**
 * @export
 * @interface NotificationEntity
 */
export interface NotificationEntity {
    /**
     * @type {string}
     * @memberof NotificationEntity
     */
    'type': 'REVIEW' | 'COLLECTION' | 'ALBUM' | 'USER';
    /**
     * @type {number}
     * @memberof NotificationEntity
     */
    'id': number;
}


/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * 알림 ID
     * @type {number}
     * @memberof Notification
     */
    'id': number;
    /**
     * 알림 유형
     * @type {string}
     * @memberof Notification
     */
    'type': NotificationTypeEnum;
    /**
     * 
     * @type {NotificationActor}
     * @memberof Notification
     */
    'actor': NotificationActor;
    /**
     * 
     * @type {NotificationEntity}
     * @memberof Notification
     */
    'entity': NotificationEntity;
    /**
     * 알림 메시지
     * @type {string}
     * @memberof Notification
     */
    'message': string;
    /**
     * 읽음 여부
     * @type {boolean}
     * @memberof Notification
     */
    'isRead': boolean;
    /**
     * 알림 생성 시각
     * @type {string}
     * @memberof Notification
     */
    'createdAt': string;
}

/**
* @export
* @enum {string}
*/
export enum NotificationTypeEnum {
    ReviewCreated = 'REVIEW_CREATED',
    UserFollowedYou = 'USER_FOLLOWED_YOU',
    CollectionLiked = 'COLLECTION_LIKED',
    ReviewLiked = 'REVIEW_LIKED',
    AlbumLiked = 'ALBUM_LIKED'
}
