/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NotificationEntity
 */
export interface NotificationEntity {
    /**
     * 참조된 엔티티 종류
     * @type {string}
     * @memberof NotificationEntity
     */
    'type'?: NotificationEntityTypeEnum;
    /**
     * 엔티티 ID
     * @type {number}
     * @memberof NotificationEntity
     */
    'id'?: number;
}

export const NotificationEntityTypeEnum = {
    Review: 'REVIEW',
    Collection: 'COLLECTION',
    Album: 'ALBUM',
    User: 'USER'
} as const;

export type NotificationEntityTypeEnum = typeof NotificationEntityTypeEnum[keyof typeof NotificationEntityTypeEnum];


