/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RatingDistribution
 */
export interface RatingDistribution {
    /**
     * 별점 0.5개 개수
     * @type {number}
     * @memberof RatingDistribution
     */
    '0.5': number;
    /**
     * 별점 1.0개 개수
     * @type {number}
     * @memberof RatingDistribution
     */
    '1.0': number;
    /**
     * 별점 1.5개 개수
     * @type {number}
     * @memberof RatingDistribution
     */
    '1.5': number;
    /**
     * 별점 2.0개 개수
     * @type {number}
     * @memberof RatingDistribution
     */
    '2.0': number;
    /**
     * 별점 2.5개 개수
     * @type {number}
     * @memberof RatingDistribution
     */
    '2.5': number;
    /**
     * 별점 3.0개 개수
     * @type {number}
     * @memberof RatingDistribution
     */
    '3.0': number;
    /**
     * 별점 3.5개 개수
     * @type {number}
     * @memberof RatingDistribution
     */
    '3.5': number;
    /**
     * 별점 4.0개 개수
     * @type {number}
     * @memberof RatingDistribution
     */
    '4.0': number;
    /**
     * 별점 4.5개 개수
     * @type {number}
     * @memberof RatingDistribution
     */
    '4.5': number;
    /**
     * 별점 5.0개 개수
     * @type {number}
     * @memberof RatingDistribution
     */
    '5.0': number;
}

