/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Top5 } from './top5';

/**
 * 
 * @export
 * @interface RecommendGet200Response
 */
export interface RecommendGet200Response {
    /**
     * 
     * @type {number}
     * @memberof RecommendGet200Response
     */
    'userId': number;
    /**
     * 
     * @type {number}
     * @memberof RecommendGet200Response
     */
    'topK': number;
    /**
     * 
     * @type {Top5}
     * @memberof RecommendGet200Response
     */
    'collections': Top5;
}

