/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReissueTokenRequest
 */
export interface ReissueTokenRequest {
    /**
     * 새로운 AccessToken을 발급받기 위한 RefreshToken
     * @type {string}
     * @memberof ReissueTokenRequest
     */
    'refreshToken': string;
}

