/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SearchResult } from './search-result';

/**
 * 
 * @export
 * @interface Search200Response1AllOfData
 */
export interface Search200Response1AllOfData {
    /**
     * 검색 결과 목록
     * @type {Array<SearchResult>}
     * @memberof Search200Response1AllOfData
     */
    'results'?: Array<SearchResult>;
    /**
     * 전체 검색 결과 개수
     * @type {number}
     * @memberof Search200Response1AllOfData
     */
    'total'?: number;
}

