/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SuccessResponse
 */
export interface SuccessResponse {
    /**
     * 요청 성공 여부
     * @type {boolean}
     * @memberof SuccessResponse
     */
    'success': boolean;
    /**
     * 응답 데이터
     * @type {object}
     * @memberof SuccessResponse
     */
    'data': object;
    /**
     * 추가 메시지 (선택사항)
     * @type {string}
     * @memberof SuccessResponse
     */
    'message'?: string;
}

