/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ToggleReviewLike200ResponseAllOfData
 */
export interface ToggleReviewLike200ResponseAllOfData {
    /**
     * 현재 좋아요 상태 (true: 좋아요 활성, false: 좋아요 취소)
     * @type {boolean}
     * @memberof ToggleReviewLike200ResponseAllOfData
     */
    'liked'?: boolean;
}

