/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Top5
 */
export interface Top5 {
    /**
     * 
     * @type {number}
     * @memberof Top5
     */
    'collectionId': number;
    /**
     * 
     * @type {number}
     * @memberof Top5
     */
    'score': number;
}

