/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RatingDistribution } from './rating-distribution';

/**
 * 
 * @export
 * @interface TrackDetailRating
 */
export interface TrackDetailRating {
    /**
     * 평균 평점
     * @type {number}
     * @memberof TrackDetailRating
     */
    'averageRating': number;
    /**
     * 총 평가 참여자 수
     * @type {number}
     * @memberof TrackDetailRating
     */
    'totalParticipants': number;
    /**
     * 
     * @type {RatingDistribution}
     * @memberof TrackDetailRating
     */
    'distribution': RatingDistribution;
}

