/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateCollectionRequest
 */
export interface UpdateCollectionRequest {
    /**
     * 수정할 제목
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    'title': string;
    /**
     * 수정할 설명
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    'description': string;
    /**
     * 수정할 공개 여부
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    'visibility': UpdateCollectionRequestVisibilityEnum;
    /**
     * 수정할 커버 이미지 URL
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    'coverImageUrl': string;
    /**
     * 수정할 태그 목록
     * @type {Array<string>}
     * @memberof UpdateCollectionRequest
     */
    'tags': Array<string>;
}

export const UpdateCollectionRequestVisibilityEnum = {
    Public: 'public',
    Private: 'private'
} as const;

export type UpdateCollectionRequestVisibilityEnum = typeof UpdateCollectionRequestVisibilityEnum[keyof typeof UpdateCollectionRequestVisibilityEnum];


