/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdatePreferencePost200Response
 */
export interface UpdatePreferencePost200Response {
    /**
     * 
     * @type {boolean}
     * @memberof UpdatePreferencePost200Response
     */
    'ok': boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdatePreferencePost200Response
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePreferencePost200Response
     */
    'error': string;
}

