/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateComment200ResponseAllOfData
 */
export interface UpdateComment200ResponseAllOfData {
    /**
     * 수정된 댓글 ID
     * @type {string}
     * @memberof UpdateComment200ResponseAllOfData
     */
    'commentId'?: string;
    /**
     * 작성자 ID
     * @type {string}
     * @memberof UpdateComment200ResponseAllOfData
     */
    'userId'?: string;
    /**
     * 작성자 닉네임
     * @type {string}
     * @memberof UpdateComment200ResponseAllOfData
     */
    'username'?: string;
    /**
     * 수정된 댓글 내용
     * @type {string}
     * @memberof UpdateComment200ResponseAllOfData
     */
    'content'?: string;
    /**
     * 수정일시
     * @type {string}
     * @memberof UpdateComment200ResponseAllOfData
     */
    'updatedAt'?: string;
}

