/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateReviewRequest
 */
export interface UpdateReviewRequest {
    /**
     * 수정할 별점
     * @type {number}
     * @memberof UpdateReviewRequest
     */
    'rating': number;
    /**
     * 수정할 제목
     * @type {string}
     * @memberof UpdateReviewRequest
     */
    'title'?: string;
    /**
     * 수정할 내용
     * @type {string}
     * @memberof UpdateReviewRequest
     */
    'content'?: string;
    /**
     * 리뷰 타입
     * @type {string}
     * @memberof UpdateReviewRequest
     */
    'type': UpdateReviewRequestTypeEnum;
}

export const UpdateReviewRequestTypeEnum = {
    Album: 'album',
    Track: 'track'
} as const;

export type UpdateReviewRequestTypeEnum = typeof UpdateReviewRequestTypeEnum[keyof typeof UpdateReviewRequestTypeEnum];


