/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CollectionPreview } from './collection-preview';
// May contain unused imports in some cases
// @ts-ignore
import type { RatedAlbum } from './rated-album';
// May contain unused imports in some cases
// @ts-ignore
import type { RatedTrack } from './rated-track';
// May contain unused imports in some cases
// @ts-ignore
import type { RatingDistribution } from './rating-distribution';

/**
 * 
 * @export
 * @interface UserDetail
 */
export interface UserDetail {
    /**
     * 사용자 ID
     * @type {number}
     * @memberof UserDetail
     */
    'userId': number;
    /**
     * 사용자 닉네임
     * @type {string}
     * @memberof UserDetail
     */
    'username': string;
    /**
     * 사용자 소개글
     * @type {string}
     * @memberof UserDetail
     */
    'bio': string;
    /**
     * 프로필 이미지 URL
     * @type {string}
     * @memberof UserDetail
     */
    'profileImageUrl': string;
    /**
     * 받은 좋아요 개수
     * @type {number}
     * @memberof UserDetail
     */
    'likeCount': number;
    /**
     * 내용이 있는 리뷰 개수
     * @type {number}
     * @memberof UserDetail
     */
    'contentReviewCount': number;
    /**
     * 평가한 앨범 개수
     * @type {number}
     * @memberof UserDetail
     */
    'albumReviewCount': number;
    /**
     * 평가한 트랙 개수
     * @type {number}
     * @memberof UserDetail
     */
    'trackReviewCount': number;
    /**
     * 좋아요한 아티스트 수
     * @type {number}
     * @memberof UserDetail
     */
    'likedArtistCount': number;
    /**
     * 
     * @type {RatingDistribution}
     * @memberof UserDetail
     */
    'rateDistribution': RatingDistribution;
    /**
     * 평가한 앨범 미리보기
     * @type {Array<RatedAlbum>}
     * @memberof UserDetail
     */
    'ratedAlbums': Array<RatedAlbum>;
    /**
     * 평가한 트랙 미리보기
     * @type {Array<RatedTrack>}
     * @memberof UserDetail
     */
    'ratedTracks': Array<RatedTrack>;
    /**
     * 내가 만든 컬렉션
     * @type {Array<CollectionPreview>}
     * @memberof UserDetail
     */
    'myCollections': Array<CollectionPreview>;
    /**
     * 좋아요한 컬렉션
     * @type {Array<CollectionPreview>}
     * @memberof UserDetail
     */
    'likedCollections': Array<CollectionPreview>;
}

