/* tslint:disable */
/* eslint-disable */
/**
 * Renew
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserPreview
 */
export interface UserPreview {
    /**
     * 사용자 ID
     * @type {number}
     * @memberof UserPreview
     */
    'id': number;
    /**
     * 사용자 닉네임
     * @type {string}
     * @memberof UserPreview
     */
    'username': string;
    /**
     * 프로필 이미지 URL
     * @type {string}
     * @memberof UserPreview
     */
    'imageUrl': string;
}

